# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from forgepoint.serving.v1 import serving_pb2 as forgepoint_dot_serving_dot_v1_dot_serving__pb2


class ModelServingServiceStub:
    """============================================================================
    NO EVENT-PAYLOAD MESSAGES HERE — BY DESIGN
    ============================================================================

    A serving pod publishes NOTHING on the NATS bus. The three former event
    messages (ModelLoadedEvent, PredictionCompletedEvent, ModelUnloadedEvent)
    were DELETED when the platform adopted the canonical event contract
    (proto/forgepoint/events/v1/events.proto). See the EVENTING block at the top
    of this file for the full rationale. In short:
    - The single inference/metering event is the gateway's
    events.InferenceCompleted (the gateway owns latency/served-version/
    principal/canary) — a serving pod must not emit a competing one.
    - The authoritative deploy lifecycle is the orchestrator saga's
    events.ModelDeployed / events.ModelUndeployed — a serving pod loading or
    unloading a model is an implementation detail of that saga, not a second
    source of truth.
    Serving CONSUMES events.{ModelVersionReady, ModelDeployed, ModelUndeployed,
    ModelPromoted, ModelArchived} (unmarshalled in Go at the consume boundary by
    the per-version-Deployment controller) and reacts via the LoadModel /
    UnloadModel control-plane RPCs below. Because this proto declares and
    references no event type, it does NOT import events.proto — importing without
    use would violate the decoupling rule and Buf's import hygiene.

    ============================================================================
    MODEL SERVING SERVICE
    ============================================================================

    WHY one ModelServingService split into a data plane and a control plane:
    - DATA PLANE (Predict, StreamPredict): the hot path, latency-critical,
    called only by the Inference Gateway, scaled by the HPA. Minimal,
    stateless, auth-agnostic — see the Sidecar rationale at the top.
    - CONTROL PLANE (LoadModel, UnloadModel, GetModelStatus, GetModelInfo,
    GetServingMetrics, HealthCheck): low-frequency lifecycle/observability
    calls made by the operator/controller, probes, and metric adapters.

    They share one service (not two) because they target the SAME pod and the
    same in-memory model; a separate AdminService would just add a second
    listener for no isolation benefit on a single-model pod. Authorization is
    enforced by the interceptor chain (the gateway's identity may Predict;
    only the operator's identity may LoadModel/UnloadModel).

    RPC CATEGORIES:
    DATA PLANE:    Predict, StreamPredict
    INTROSPECTION: GetModelInfo, ListLoadedModels
    LIFECYCLE:     LoadModel, UnloadModel, GetModelStatus
    AUTOSCALING:   GetServingMetrics
    PROBES:        HealthCheck

    NONE of these RPCs publish an event — the data plane returns inline and the
    control plane mutates pod-local state; the platform's record of what served
    (events.InferenceCompleted) and what is deployed (events.ModelDeployed/
    Undeployed) is produced by the gateway and orchestrator respectively.

    ASCII — where each RPC sits:

    ┌───────────────── Inference Gateway ─────────────────┐
    │  Predict / StreamPredict  ──────►  (data plane, HPA-scaled) │
    │  GetServingMetrics  ──────►  least-inflight routing         │
    └────────────────────────────────────────────────────┘
    ┌──────────── Operator / Controller ─────────────────┐
    │  LoadModel / UnloadModel / GetModelStatus / ListLoadedModels ►│
    │  (driven by consumed ModelDeployed/Undeployed/Promoted/...)  │
    └────────────────────────────────────────────────────┘
    ┌──────────────────── Kubelet ───────────────────────┐
    │  HealthCheck (readiness=READY, liveness=latency<thr)────────►│
    └────────────────────────────────────────────────────┘
    ============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/forgepoint.serving.v1.ModelServingService/Predict',
                request_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.PredictRequest.SerializeToString,
                response_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.StreamPredict = channel.stream_stream(
                '/forgepoint.serving.v1.ModelServingService/StreamPredict',
                request_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.StreamPredictRequest.SerializeToString,
                response_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.StreamPredictResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/forgepoint.serving.v1.ModelServingService/GetModelInfo',
                request_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetModelInfoResponse.FromString,
                _registered_method=True)
        self.ListLoadedModels = channel.unary_unary(
                '/forgepoint.serving.v1.ModelServingService/ListLoadedModels',
                request_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.ListLoadedModelsRequest.SerializeToString,
                response_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.ListLoadedModelsResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/forgepoint.serving.v1.ModelServingService/LoadModel',
                request_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.UnloadModel = channel.unary_unary(
                '/forgepoint.serving.v1.ModelServingService/UnloadModel',
                request_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.UnloadModelRequest.SerializeToString,
                response_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.UnloadModelResponse.FromString,
                _registered_method=True)
        self.GetModelStatus = channel.unary_unary(
                '/forgepoint.serving.v1.ModelServingService/GetModelStatus',
                request_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetModelStatusRequest.SerializeToString,
                response_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetModelStatusResponse.FromString,
                _registered_method=True)
        self.GetServingMetrics = channel.unary_unary(
                '/forgepoint.serving.v1.ModelServingService/GetServingMetrics',
                request_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetServingMetricsRequest.SerializeToString,
                response_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetServingMetricsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/forgepoint.serving.v1.ModelServingService/HealthCheck',
                request_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ModelServingServiceServicer:
    """============================================================================
    NO EVENT-PAYLOAD MESSAGES HERE — BY DESIGN
    ============================================================================

    A serving pod publishes NOTHING on the NATS bus. The three former event
    messages (ModelLoadedEvent, PredictionCompletedEvent, ModelUnloadedEvent)
    were DELETED when the platform adopted the canonical event contract
    (proto/forgepoint/events/v1/events.proto). See the EVENTING block at the top
    of this file for the full rationale. In short:
    - The single inference/metering event is the gateway's
    events.InferenceCompleted (the gateway owns latency/served-version/
    principal/canary) — a serving pod must not emit a competing one.
    - The authoritative deploy lifecycle is the orchestrator saga's
    events.ModelDeployed / events.ModelUndeployed — a serving pod loading or
    unloading a model is an implementation detail of that saga, not a second
    source of truth.
    Serving CONSUMES events.{ModelVersionReady, ModelDeployed, ModelUndeployed,
    ModelPromoted, ModelArchived} (unmarshalled in Go at the consume boundary by
    the per-version-Deployment controller) and reacts via the LoadModel /
    UnloadModel control-plane RPCs below. Because this proto declares and
    references no event type, it does NOT import events.proto — importing without
    use would violate the decoupling rule and Buf's import hygiene.

    ============================================================================
    MODEL SERVING SERVICE
    ============================================================================

    WHY one ModelServingService split into a data plane and a control plane:
    - DATA PLANE (Predict, StreamPredict): the hot path, latency-critical,
    called only by the Inference Gateway, scaled by the HPA. Minimal,
    stateless, auth-agnostic — see the Sidecar rationale at the top.
    - CONTROL PLANE (LoadModel, UnloadModel, GetModelStatus, GetModelInfo,
    GetServingMetrics, HealthCheck): low-frequency lifecycle/observability
    calls made by the operator/controller, probes, and metric adapters.

    They share one service (not two) because they target the SAME pod and the
    same in-memory model; a separate AdminService would just add a second
    listener for no isolation benefit on a single-model pod. Authorization is
    enforced by the interceptor chain (the gateway's identity may Predict;
    only the operator's identity may LoadModel/UnloadModel).

    RPC CATEGORIES:
    DATA PLANE:    Predict, StreamPredict
    INTROSPECTION: GetModelInfo, ListLoadedModels
    LIFECYCLE:     LoadModel, UnloadModel, GetModelStatus
    AUTOSCALING:   GetServingMetrics
    PROBES:        HealthCheck

    NONE of these RPCs publish an event — the data plane returns inline and the
    control plane mutates pod-local state; the platform's record of what served
    (events.InferenceCompleted) and what is deployed (events.ModelDeployed/
    Undeployed) is produced by the gateway and orchestrator respectively.

    ASCII — where each RPC sits:

    ┌───────────────── Inference Gateway ─────────────────┐
    │  Predict / StreamPredict  ──────►  (data plane, HPA-scaled) │
    │  GetServingMetrics  ──────►  least-inflight routing         │
    └────────────────────────────────────────────────────┘
    ┌──────────── Operator / Controller ─────────────────┐
    │  LoadModel / UnloadModel / GetModelStatus / ListLoadedModels ►│
    │  (driven by consumed ModelDeployed/Undeployed/Promoted/...)  │
    └────────────────────────────────────────────────────┘
    ┌──────────────────── Kubelet ───────────────────────┐
    │  HealthCheck (readiness=READY, liveness=latency<thr)────────►│
    └────────────────────────────────────────────────────┘
    ============================================================================
    """

    def Predict(self, request, context):
        """Predict runs a single synchronous inference. The hot path; called by the
        Inference Gateway after it has authed, rate-limited, and chosen a version.
        NO side effect on the bus: the pod returns the result and the GATEWAY
        publishes events.InferenceCompleted (billing + monitor consume that single
        canonical event). Idempotent on idempotency_key purely to make gateway
        retries cheap (result cache, not a billing concern).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPredict(self, request_iterator, context):
        """StreamPredict is a bidirectional stream for high-throughput batch scoring
        or long-lived online feeds. Opt-in (unary Predict is the primary path).
        Each request message carries its own idempotency_key; responses are not
        1:1-ordered with requests, so clients pair them via that key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """GetModelInfo returns the served model's identity + I/O schema so clients
        can build valid Predict requests. All fields server-authoritative.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLoadedModels(self, request, context):
        """ListLoadedModels returns the live status of every model resident on the pod
        (0..1 today; forward-compatible with multi-model). Paginated (common.v1;
        page_size server-clamped to [1,100]). The reconcile loop uses it to compare
        desired (consumed ModelDeployed events) vs actual (resident) models.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """LoadModel pulls an artifact from object storage and loads it into the ONNX
        runtime. Admin/controller-only — typically driven by a consumed
        events.ModelDeployed / events.ModelVersionReady. Load is async — poll
        GetModelStatus for READY. Idempotent: re-loading an already-READY identical
        (name,version,digest) is a no-op returning current status. SSRF-guarded:
        artifact_uri is validated against the pod's allow-listed bucket/prefix.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadModel(self, request, context):
        """UnloadModel frees the model from memory. Admin/controller-only — typically
        driven by a consumed events.ModelUndeployed / events.ModelArchived. After
        unload Predict returns FAILED_PRECONDITION. Publishes NO event (the
        authoritative teardown fact is the orchestrator's events.ModelUndeployed).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelStatus(self, request, context):
        """GetModelStatus returns the live lifecycle state (DOWNLOADING/LOADING/READY/
        FAILED/UNLOADED). Used by the operator's reconcile loop and admin tooling.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServingMetrics(self, request, context):
        """GetServingMetrics returns the inflight/latency snapshot that drives the HPA
        (custom-metrics autoscaling) and the gateway's least-inflight routing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck reports serving readiness (model loaded) + the latency signal
        behind liveness. Wired to K8s readiness/liveness probes for this per-model
        Deployment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.PredictRequest.FromString,
                    response_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.PredictResponse.SerializeToString,
            ),
            'StreamPredict': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPredict,
                    request_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.StreamPredictRequest.FromString,
                    response_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.StreamPredictResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetModelInfoRequest.FromString,
                    response_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetModelInfoResponse.SerializeToString,
            ),
            'ListLoadedModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLoadedModels,
                    request_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.ListLoadedModelsRequest.FromString,
                    response_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.ListLoadedModelsResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.LoadModelRequest.FromString,
                    response_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.LoadModelResponse.SerializeToString,
            ),
            'UnloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadModel,
                    request_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.UnloadModelRequest.FromString,
                    response_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.UnloadModelResponse.SerializeToString,
            ),
            'GetModelStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelStatus,
                    request_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetModelStatusRequest.FromString,
                    response_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetModelStatusResponse.SerializeToString,
            ),
            'GetServingMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServingMetrics,
                    request_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetServingMetricsRequest.FromString,
                    response_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetServingMetricsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.HealthCheckRequest.FromString,
                    response_serializer=forgepoint_dot_serving_dot_v1_dot_serving__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forgepoint.serving.v1.ModelServingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forgepoint.serving.v1.ModelServingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelServingService:
    """============================================================================
    NO EVENT-PAYLOAD MESSAGES HERE — BY DESIGN
    ============================================================================

    A serving pod publishes NOTHING on the NATS bus. The three former event
    messages (ModelLoadedEvent, PredictionCompletedEvent, ModelUnloadedEvent)
    were DELETED when the platform adopted the canonical event contract
    (proto/forgepoint/events/v1/events.proto). See the EVENTING block at the top
    of this file for the full rationale. In short:
    - The single inference/metering event is the gateway's
    events.InferenceCompleted (the gateway owns latency/served-version/
    principal/canary) — a serving pod must not emit a competing one.
    - The authoritative deploy lifecycle is the orchestrator saga's
    events.ModelDeployed / events.ModelUndeployed — a serving pod loading or
    unloading a model is an implementation detail of that saga, not a second
    source of truth.
    Serving CONSUMES events.{ModelVersionReady, ModelDeployed, ModelUndeployed,
    ModelPromoted, ModelArchived} (unmarshalled in Go at the consume boundary by
    the per-version-Deployment controller) and reacts via the LoadModel /
    UnloadModel control-plane RPCs below. Because this proto declares and
    references no event type, it does NOT import events.proto — importing without
    use would violate the decoupling rule and Buf's import hygiene.

    ============================================================================
    MODEL SERVING SERVICE
    ============================================================================

    WHY one ModelServingService split into a data plane and a control plane:
    - DATA PLANE (Predict, StreamPredict): the hot path, latency-critical,
    called only by the Inference Gateway, scaled by the HPA. Minimal,
    stateless, auth-agnostic — see the Sidecar rationale at the top.
    - CONTROL PLANE (LoadModel, UnloadModel, GetModelStatus, GetModelInfo,
    GetServingMetrics, HealthCheck): low-frequency lifecycle/observability
    calls made by the operator/controller, probes, and metric adapters.

    They share one service (not two) because they target the SAME pod and the
    same in-memory model; a separate AdminService would just add a second
    listener for no isolation benefit on a single-model pod. Authorization is
    enforced by the interceptor chain (the gateway's identity may Predict;
    only the operator's identity may LoadModel/UnloadModel).

    RPC CATEGORIES:
    DATA PLANE:    Predict, StreamPredict
    INTROSPECTION: GetModelInfo, ListLoadedModels
    LIFECYCLE:     LoadModel, UnloadModel, GetModelStatus
    AUTOSCALING:   GetServingMetrics
    PROBES:        HealthCheck

    NONE of these RPCs publish an event — the data plane returns inline and the
    control plane mutates pod-local state; the platform's record of what served
    (events.InferenceCompleted) and what is deployed (events.ModelDeployed/
    Undeployed) is produced by the gateway and orchestrator respectively.

    ASCII — where each RPC sits:

    ┌───────────────── Inference Gateway ─────────────────┐
    │  Predict / StreamPredict  ──────►  (data plane, HPA-scaled) │
    │  GetServingMetrics  ──────►  least-inflight routing         │
    └────────────────────────────────────────────────────┘
    ┌──────────── Operator / Controller ─────────────────┐
    │  LoadModel / UnloadModel / GetModelStatus / ListLoadedModels ►│
    │  (driven by consumed ModelDeployed/Undeployed/Promoted/...)  │
    └────────────────────────────────────────────────────┘
    ┌──────────────────── Kubelet ───────────────────────┐
    │  HealthCheck (readiness=READY, liveness=latency<thr)────────►│
    └────────────────────────────────────────────────────┘
    ============================================================================
    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.serving.v1.ModelServingService/Predict',
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.PredictRequest.SerializeToString,
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPredict(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/forgepoint.serving.v1.ModelServingService/StreamPredict',
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.StreamPredictRequest.SerializeToString,
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.StreamPredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.serving.v1.ModelServingService/GetModelInfo',
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetModelInfoRequest.SerializeToString,
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLoadedModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.serving.v1.ModelServingService/ListLoadedModels',
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.ListLoadedModelsRequest.SerializeToString,
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.ListLoadedModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.serving.v1.ModelServingService/LoadModel',
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.LoadModelRequest.SerializeToString,
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.serving.v1.ModelServingService/UnloadModel',
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.UnloadModelRequest.SerializeToString,
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.UnloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.serving.v1.ModelServingService/GetModelStatus',
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetModelStatusRequest.SerializeToString,
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetModelStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServingMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.serving.v1.ModelServingService/GetServingMetrics',
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetServingMetricsRequest.SerializeToString,
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.GetServingMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.serving.v1.ModelServingService/HealthCheck',
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.HealthCheckRequest.SerializeToString,
            forgepoint_dot_serving_dot_v1_dot_serving__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
