# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from forgepoint.featurestore.v1 import featurestore_pb2 as forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2


class FeatureStoreServiceStub:
    """============================================================================
    EVENT PAYLOADS — NOW CANONICAL (forgepoint.events.v1), NOT redefined here
    ============================================================================

    The Feature Store PRODUCES two events. Their payload messages used to live in
    THIS file; they have been MOVED to the platform's single canonical event
    package and DELETED here. Producers pack the canonical messages into
    common.v1.EventEnvelope.data (a google.protobuf.Any); consumers unpack the
    SAME message by its Any type_url — one contract, both ends of every pipe.

    WHAT THE FEATURE STORE PUBLISHES (producer = "feature-store"):
    fp.features.view.defined  → forgepoint.events.v1.FeatureViewDefined
    fp.features.written       → forgepoint.events.v1.FeaturesWritten

    WHO CONSUMES (informational — defined by the consumers, not us):
    FeatureViewDefined → experiment-tracker (correlate which feature schema
    versions fed a training run), audit subscribers.
    FeaturesWritten    → experiment-tracker (which feature versions fed a
    run), model-monitor (scope drift checks / cache
    invalidation to the changed entities).

    WHY MOVED (the bug this fixes — conflict #4 in events.proto):
    The platform's async nervous system had DRIFTED. The design doc and the
    experiment-tracker subscribed to "fp.features.ingested" / "FeaturesIngested",
    while this service published "FeaturesWritten" on "fp.features.written".
    Same fact, two names — the subscription would NEVER fire. Centralizing the
    payloads in forgepoint.events.v1 makes that class of mismatch impossible:
    producer and consumer literally import the same generated Go type. (The
    experiment-tracker fix repoints its subscription to fp.features.written.)

    It also DECOUPLES the event schema from this service's API schema. The old
    local messages were fine until you ask: should the Experiment Tracker
    compile-depend on featurestore.proto just to read an event? No. The event is
    a separately-versioned PUBLISHED CONTRACT (schema-registry thinking); it
    imports only well-known types + common, never a service's API proto.

    THIN-BY-DESIGN (unchanged, and codified in the canonical message):
    events.FeaturesWritten carries the affected entity_ids + a count +
    written_through_version — NOT the feature VALUES. Events are for
    NOTIFICATION/correlation; a consumer that needs the actual values calls
    GetOnlineFeatures/GetHistoricalFeatures (the read models below). This keeps
    NATS small and stops the bus becoming a second source of truth. (This is the
    "thin event + callback" side of the fat-vs-thin tradeoff — chosen here
    because feature rows are large and only some consumers want the values.)

    PUBLISHER FIELD MAPPING (a few lines in the handler at the publish boundary —
    the price of decoupling, and the only thing the rename touches):
    DefineFeatureView success →  events.FeatureViewDefined{
    feature_view_id   = view.id
    feature_view_name = view.name        // canonical field is feature_view_name
    schema_version    = view.schema_version
    owner_team        = view.owner_team
    defined_at        = view.updated_at  // RENAMED: old local occurred_at → defined_at
    }
    WriteFeatures success →      events.FeaturesWritten{
    feature_view_id          = req.feature_view_id
    feature_view_name        = view.name
    entity_ids               = affected ids (MAY be truncated; count is authoritative)
    written_count            = rows appended
    written_through_version  = resp.written_through_version
    written_at               = append commit time  // RENAMED: old occurred_at → written_at
    }
    The canonical messages live in proto/forgepoint/events/v1/events.proto under
    the "FEATURE-STORE EVENTS" section — read there for field-level docs.

    ============================================================================
    FEATURE STORE SERVICE
    ============================================================================

    WHY one FeatureStoreService (not split into Catalog/Write/Serve services):
    definition (schema), ingestion (append), and serving (project) all operate
    on the SAME event log and views and share the same team-ownership boundary.
    Splitting them would force inter-service calls and a shared event store
    across service boundaries — violating database-per-service. They live
    behind one boundary; CQRS happens INSIDE this service (write model = event
    log; read models = Redis online + Postgres offline), not across services.

    RPC CATEGORIES:
    DEFINITION (catalog):  DefineFeatureView, GetFeatureView, ListFeatureViews
    WRITE (commands):      WriteFeatures                 → appends events
    READ (projections):    GetOnlineFeatures (latest),
    GetHistoricalFeatures (point-in-time)
    ADMIN (lifecycle):     DeleteFeatureView (soft retire → FeatureViewDeleted),
    RebuildViews (replay log → regenerate projections)

    SERVER-ENFORCED LIMITS (in the CONTRACT, not just prose — see each RPC):
    * page_size (ListFeatureViews, GetHistoricalFeatures): default 20, hard cap
    MAX_PAGE_SIZE = 100 (oversized requests are CLAMPED, not rejected).
    * batch size (entity_ids on GetOnline/GetHistorical; features on Write):
    hard cap MAX_BATCH_SIZE = 1000 entities/rows; OVER-cap requests are
    REJECTED with INVALID_ARGUMENT (a too-large write must fail loudly, not be
    silently truncated — truncation would drop feature rows). proto3 has no
    native numeric bound, so these caps are documented as named constants and
    enforced server-side; the constants are the contract.

    STREAMING CHOICE (interview-critical):
    DATA-PLANE RPCs are UNARY; the long-running ADMIN replay is SERVER-STREAMING.
    - WriteFeatures: producers emit in BATCHES (one RPC = one atomic append
    with one idempotency key). Client-streaming would blur the idempotency/
    atomicity boundary (when is the append "committed"?). Bounded batches +
    idempotency key is simpler and safer.
    - GetOnlineFeatures: a single fast key→value projection read; sub-ms
    budget on the inference hot path — streaming overhead is unwarranted.
    - GetHistoricalFeatures: bounded, PAGINATED point-in-time pulls. Truly
    huge training joins are an offline batch job (export to object storage),
    not a synchronous server stream — a deliberate later refinement.
    - RebuildViews: SERVER-STREAMING — a full log replay runs for minutes, so
    we stream RebuildViewsResponse frames for live feedback and use stream-close as the
    completion signal (no poll loop). Note this is justified by DURATION, not
    data volume — the contrast with the unary reads is the interview point.
    So the only streaming RPC is the admin replay, deliberately, and every choice
    is documented so it is defensible.

    EVENT-SOURCING RECAP (what an interviewer will probe):
    * Source of truth = append-only feature_events log. Views are caches.
    * Reads never replay on the hot path; they read projections.
    * Reproducibility = GetHistoricalFeatures(as_of) over event_time.
    * Recovery = RebuildViews replays the log to rebuild Redis + Postgres views.
    * Soft delete = DeleteFeatureView appends a terminal event; history is kept.
    * Exactly-once EFFECT under retries = idempotency_key on mutating RPCs.
    * Eventual consistency online = surfaced via as_of_version in reads.
    * Async contract = publishes forgepoint.events.v1 FeatureViewDefined /
    FeaturesWritten (canonical, decoupled from this API proto).
    ============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DefineFeatureView = channel.unary_unary(
                '/forgepoint.featurestore.v1.FeatureStoreService/DefineFeatureView',
                request_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.DefineFeatureViewRequest.SerializeToString,
                response_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.DefineFeatureViewResponse.FromString,
                _registered_method=True)
        self.GetFeatureView = channel.unary_unary(
                '/forgepoint.featurestore.v1.FeatureStoreService/GetFeatureView',
                request_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetFeatureViewRequest.SerializeToString,
                response_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetFeatureViewResponse.FromString,
                _registered_method=True)
        self.ListFeatureViews = channel.unary_unary(
                '/forgepoint.featurestore.v1.FeatureStoreService/ListFeatureViews',
                request_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.ListFeatureViewsRequest.SerializeToString,
                response_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.ListFeatureViewsResponse.FromString,
                _registered_method=True)
        self.WriteFeatures = channel.unary_unary(
                '/forgepoint.featurestore.v1.FeatureStoreService/WriteFeatures',
                request_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.WriteFeaturesRequest.SerializeToString,
                response_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.WriteFeaturesResponse.FromString,
                _registered_method=True)
        self.GetOnlineFeatures = channel.unary_unary(
                '/forgepoint.featurestore.v1.FeatureStoreService/GetOnlineFeatures',
                request_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetOnlineFeaturesRequest.SerializeToString,
                response_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetOnlineFeaturesResponse.FromString,
                _registered_method=True)
        self.GetHistoricalFeatures = channel.unary_unary(
                '/forgepoint.featurestore.v1.FeatureStoreService/GetHistoricalFeatures',
                request_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetHistoricalFeaturesRequest.SerializeToString,
                response_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetHistoricalFeaturesResponse.FromString,
                _registered_method=True)
        self.DeleteFeatureView = channel.unary_unary(
                '/forgepoint.featurestore.v1.FeatureStoreService/DeleteFeatureView',
                request_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.DeleteFeatureViewRequest.SerializeToString,
                response_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.DeleteFeatureViewResponse.FromString,
                _registered_method=True)
        self.RebuildViews = channel.unary_stream(
                '/forgepoint.featurestore.v1.FeatureStoreService/RebuildViews',
                request_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.RebuildViewsRequest.SerializeToString,
                response_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.RebuildViewsResponse.FromString,
                _registered_method=True)


class FeatureStoreServiceServicer:
    """============================================================================
    EVENT PAYLOADS — NOW CANONICAL (forgepoint.events.v1), NOT redefined here
    ============================================================================

    The Feature Store PRODUCES two events. Their payload messages used to live in
    THIS file; they have been MOVED to the platform's single canonical event
    package and DELETED here. Producers pack the canonical messages into
    common.v1.EventEnvelope.data (a google.protobuf.Any); consumers unpack the
    SAME message by its Any type_url — one contract, both ends of every pipe.

    WHAT THE FEATURE STORE PUBLISHES (producer = "feature-store"):
    fp.features.view.defined  → forgepoint.events.v1.FeatureViewDefined
    fp.features.written       → forgepoint.events.v1.FeaturesWritten

    WHO CONSUMES (informational — defined by the consumers, not us):
    FeatureViewDefined → experiment-tracker (correlate which feature schema
    versions fed a training run), audit subscribers.
    FeaturesWritten    → experiment-tracker (which feature versions fed a
    run), model-monitor (scope drift checks / cache
    invalidation to the changed entities).

    WHY MOVED (the bug this fixes — conflict #4 in events.proto):
    The platform's async nervous system had DRIFTED. The design doc and the
    experiment-tracker subscribed to "fp.features.ingested" / "FeaturesIngested",
    while this service published "FeaturesWritten" on "fp.features.written".
    Same fact, two names — the subscription would NEVER fire. Centralizing the
    payloads in forgepoint.events.v1 makes that class of mismatch impossible:
    producer and consumer literally import the same generated Go type. (The
    experiment-tracker fix repoints its subscription to fp.features.written.)

    It also DECOUPLES the event schema from this service's API schema. The old
    local messages were fine until you ask: should the Experiment Tracker
    compile-depend on featurestore.proto just to read an event? No. The event is
    a separately-versioned PUBLISHED CONTRACT (schema-registry thinking); it
    imports only well-known types + common, never a service's API proto.

    THIN-BY-DESIGN (unchanged, and codified in the canonical message):
    events.FeaturesWritten carries the affected entity_ids + a count +
    written_through_version — NOT the feature VALUES. Events are for
    NOTIFICATION/correlation; a consumer that needs the actual values calls
    GetOnlineFeatures/GetHistoricalFeatures (the read models below). This keeps
    NATS small and stops the bus becoming a second source of truth. (This is the
    "thin event + callback" side of the fat-vs-thin tradeoff — chosen here
    because feature rows are large and only some consumers want the values.)

    PUBLISHER FIELD MAPPING (a few lines in the handler at the publish boundary —
    the price of decoupling, and the only thing the rename touches):
    DefineFeatureView success →  events.FeatureViewDefined{
    feature_view_id   = view.id
    feature_view_name = view.name        // canonical field is feature_view_name
    schema_version    = view.schema_version
    owner_team        = view.owner_team
    defined_at        = view.updated_at  // RENAMED: old local occurred_at → defined_at
    }
    WriteFeatures success →      events.FeaturesWritten{
    feature_view_id          = req.feature_view_id
    feature_view_name        = view.name
    entity_ids               = affected ids (MAY be truncated; count is authoritative)
    written_count            = rows appended
    written_through_version  = resp.written_through_version
    written_at               = append commit time  // RENAMED: old occurred_at → written_at
    }
    The canonical messages live in proto/forgepoint/events/v1/events.proto under
    the "FEATURE-STORE EVENTS" section — read there for field-level docs.

    ============================================================================
    FEATURE STORE SERVICE
    ============================================================================

    WHY one FeatureStoreService (not split into Catalog/Write/Serve services):
    definition (schema), ingestion (append), and serving (project) all operate
    on the SAME event log and views and share the same team-ownership boundary.
    Splitting them would force inter-service calls and a shared event store
    across service boundaries — violating database-per-service. They live
    behind one boundary; CQRS happens INSIDE this service (write model = event
    log; read models = Redis online + Postgres offline), not across services.

    RPC CATEGORIES:
    DEFINITION (catalog):  DefineFeatureView, GetFeatureView, ListFeatureViews
    WRITE (commands):      WriteFeatures                 → appends events
    READ (projections):    GetOnlineFeatures (latest),
    GetHistoricalFeatures (point-in-time)
    ADMIN (lifecycle):     DeleteFeatureView (soft retire → FeatureViewDeleted),
    RebuildViews (replay log → regenerate projections)

    SERVER-ENFORCED LIMITS (in the CONTRACT, not just prose — see each RPC):
    * page_size (ListFeatureViews, GetHistoricalFeatures): default 20, hard cap
    MAX_PAGE_SIZE = 100 (oversized requests are CLAMPED, not rejected).
    * batch size (entity_ids on GetOnline/GetHistorical; features on Write):
    hard cap MAX_BATCH_SIZE = 1000 entities/rows; OVER-cap requests are
    REJECTED with INVALID_ARGUMENT (a too-large write must fail loudly, not be
    silently truncated — truncation would drop feature rows). proto3 has no
    native numeric bound, so these caps are documented as named constants and
    enforced server-side; the constants are the contract.

    STREAMING CHOICE (interview-critical):
    DATA-PLANE RPCs are UNARY; the long-running ADMIN replay is SERVER-STREAMING.
    - WriteFeatures: producers emit in BATCHES (one RPC = one atomic append
    with one idempotency key). Client-streaming would blur the idempotency/
    atomicity boundary (when is the append "committed"?). Bounded batches +
    idempotency key is simpler and safer.
    - GetOnlineFeatures: a single fast key→value projection read; sub-ms
    budget on the inference hot path — streaming overhead is unwarranted.
    - GetHistoricalFeatures: bounded, PAGINATED point-in-time pulls. Truly
    huge training joins are an offline batch job (export to object storage),
    not a synchronous server stream — a deliberate later refinement.
    - RebuildViews: SERVER-STREAMING — a full log replay runs for minutes, so
    we stream RebuildViewsResponse frames for live feedback and use stream-close as the
    completion signal (no poll loop). Note this is justified by DURATION, not
    data volume — the contrast with the unary reads is the interview point.
    So the only streaming RPC is the admin replay, deliberately, and every choice
    is documented so it is defensible.

    EVENT-SOURCING RECAP (what an interviewer will probe):
    * Source of truth = append-only feature_events log. Views are caches.
    * Reads never replay on the hot path; they read projections.
    * Reproducibility = GetHistoricalFeatures(as_of) over event_time.
    * Recovery = RebuildViews replays the log to rebuild Redis + Postgres views.
    * Soft delete = DeleteFeatureView appends a terminal event; history is kept.
    * Exactly-once EFFECT under retries = idempotency_key on mutating RPCs.
    * Eventual consistency online = surfaced via as_of_version in reads.
    * Async contract = publishes forgepoint.events.v1 FeatureViewDefined /
    FeaturesWritten (canonical, decoupled from this API proto).
    ============================================================================
    """

    def DefineFeatureView(self, request, context):
        """DefineFeatureView creates a FeatureView or evolves its schema (append a
        FeatureViewDefined event; bump schema_version). Owner/team/timestamps are
        SERVER-assigned. Idempotent via idempotency_key. On commit, publishes
        forgepoint.events.v1.FeatureViewDefined on fp.features.view.defined.
        Requires "features:write".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeatureView(self, request, context):
        """GetFeatureView returns a SINGLE view's current schema/metadata by id or name
        (a read of the catalog projection), scoped to the caller's team. Requires
        "features:read".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFeatureViews(self, request, context):
        """ListFeatureViews returns a paginated catalog of feature views (a projection
        over FeatureViewDefined events), scoped to the caller's team. page_size
        defaults to 20 and is CAPPED at MAX_PAGE_SIZE=100 server-side (clamped).
        Requires "features:read".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFeatures(self, request, context):
        """WriteFeatures appends a batch of feature rows to the event log (the core
        event-sourcing write). Values are validated against the view schema; a type
        mismatch fails the whole batch. Batch size is capped at MAX_BATCH_SIZE=1000
        rows (over-cap → INVALID_ARGUMENT). Idempotent via idempotency_key. On
        commit, publishes forgepoint.events.v1.FeaturesWritten on fp.features.written.
        Requires "features:write".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOnlineFeatures(self, request, context):
        """GetOnlineFeatures returns the LATEST feature values for entities from the
        low-latency online projection (the inference hot path). entity_ids batch is
        capped at MAX_BATCH_SIZE=1000. Eventually consistent with writes; response
        carries as_of_version for staleness detection. Requires "features:read".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoricalFeatures(self, request, context):
        """GetHistoricalFeatures returns POINT-IN-TIME ("as-of") feature values from
        the offline projection — for each entity, the latest event with
        event_time <= as_of. Powers reproducible training and prevents label
        leakage. entity_ids batch capped at MAX_BATCH_SIZE=1000; result paginated
        with page_size capped at MAX_PAGE_SIZE=100. Requires "features:read".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFeatureView(self, request, context):
        """DeleteFeatureView soft-retires a view by appending a terminal
        FeatureViewDeleted event (the log/history is preserved for reproducibility;
        the online projection is torn down). Idempotent via idempotency_key.
        Requires "features:write".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RebuildViews(self, request, context):
        """RebuildViews replays the append-only log to regenerate the materialized
        projections (Redis online + Postgres offline) — the event-sourcing recovery
        path. SERVER-STREAMING: emits RebuildViewsResponse progress frames until done.
        This is an ADMIN op requiring the elevated "features:admin" scope (a full
        replay is expensive and sensitive — not reachable with a routine write token).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeatureStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DefineFeatureView': grpc.unary_unary_rpc_method_handler(
                    servicer.DefineFeatureView,
                    request_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.DefineFeatureViewRequest.FromString,
                    response_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.DefineFeatureViewResponse.SerializeToString,
            ),
            'GetFeatureView': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeatureView,
                    request_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetFeatureViewRequest.FromString,
                    response_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetFeatureViewResponse.SerializeToString,
            ),
            'ListFeatureViews': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFeatureViews,
                    request_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.ListFeatureViewsRequest.FromString,
                    response_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.ListFeatureViewsResponse.SerializeToString,
            ),
            'WriteFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteFeatures,
                    request_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.WriteFeaturesRequest.FromString,
                    response_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.WriteFeaturesResponse.SerializeToString,
            ),
            'GetOnlineFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOnlineFeatures,
                    request_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetOnlineFeaturesRequest.FromString,
                    response_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetOnlineFeaturesResponse.SerializeToString,
            ),
            'GetHistoricalFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoricalFeatures,
                    request_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetHistoricalFeaturesRequest.FromString,
                    response_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetHistoricalFeaturesResponse.SerializeToString,
            ),
            'DeleteFeatureView': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFeatureView,
                    request_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.DeleteFeatureViewRequest.FromString,
                    response_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.DeleteFeatureViewResponse.SerializeToString,
            ),
            'RebuildViews': grpc.unary_stream_rpc_method_handler(
                    servicer.RebuildViews,
                    request_deserializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.RebuildViewsRequest.FromString,
                    response_serializer=forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.RebuildViewsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forgepoint.featurestore.v1.FeatureStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forgepoint.featurestore.v1.FeatureStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeatureStoreService:
    """============================================================================
    EVENT PAYLOADS — NOW CANONICAL (forgepoint.events.v1), NOT redefined here
    ============================================================================

    The Feature Store PRODUCES two events. Their payload messages used to live in
    THIS file; they have been MOVED to the platform's single canonical event
    package and DELETED here. Producers pack the canonical messages into
    common.v1.EventEnvelope.data (a google.protobuf.Any); consumers unpack the
    SAME message by its Any type_url — one contract, both ends of every pipe.

    WHAT THE FEATURE STORE PUBLISHES (producer = "feature-store"):
    fp.features.view.defined  → forgepoint.events.v1.FeatureViewDefined
    fp.features.written       → forgepoint.events.v1.FeaturesWritten

    WHO CONSUMES (informational — defined by the consumers, not us):
    FeatureViewDefined → experiment-tracker (correlate which feature schema
    versions fed a training run), audit subscribers.
    FeaturesWritten    → experiment-tracker (which feature versions fed a
    run), model-monitor (scope drift checks / cache
    invalidation to the changed entities).

    WHY MOVED (the bug this fixes — conflict #4 in events.proto):
    The platform's async nervous system had DRIFTED. The design doc and the
    experiment-tracker subscribed to "fp.features.ingested" / "FeaturesIngested",
    while this service published "FeaturesWritten" on "fp.features.written".
    Same fact, two names — the subscription would NEVER fire. Centralizing the
    payloads in forgepoint.events.v1 makes that class of mismatch impossible:
    producer and consumer literally import the same generated Go type. (The
    experiment-tracker fix repoints its subscription to fp.features.written.)

    It also DECOUPLES the event schema from this service's API schema. The old
    local messages were fine until you ask: should the Experiment Tracker
    compile-depend on featurestore.proto just to read an event? No. The event is
    a separately-versioned PUBLISHED CONTRACT (schema-registry thinking); it
    imports only well-known types + common, never a service's API proto.

    THIN-BY-DESIGN (unchanged, and codified in the canonical message):
    events.FeaturesWritten carries the affected entity_ids + a count +
    written_through_version — NOT the feature VALUES. Events are for
    NOTIFICATION/correlation; a consumer that needs the actual values calls
    GetOnlineFeatures/GetHistoricalFeatures (the read models below). This keeps
    NATS small and stops the bus becoming a second source of truth. (This is the
    "thin event + callback" side of the fat-vs-thin tradeoff — chosen here
    because feature rows are large and only some consumers want the values.)

    PUBLISHER FIELD MAPPING (a few lines in the handler at the publish boundary —
    the price of decoupling, and the only thing the rename touches):
    DefineFeatureView success →  events.FeatureViewDefined{
    feature_view_id   = view.id
    feature_view_name = view.name        // canonical field is feature_view_name
    schema_version    = view.schema_version
    owner_team        = view.owner_team
    defined_at        = view.updated_at  // RENAMED: old local occurred_at → defined_at
    }
    WriteFeatures success →      events.FeaturesWritten{
    feature_view_id          = req.feature_view_id
    feature_view_name        = view.name
    entity_ids               = affected ids (MAY be truncated; count is authoritative)
    written_count            = rows appended
    written_through_version  = resp.written_through_version
    written_at               = append commit time  // RENAMED: old occurred_at → written_at
    }
    The canonical messages live in proto/forgepoint/events/v1/events.proto under
    the "FEATURE-STORE EVENTS" section — read there for field-level docs.

    ============================================================================
    FEATURE STORE SERVICE
    ============================================================================

    WHY one FeatureStoreService (not split into Catalog/Write/Serve services):
    definition (schema), ingestion (append), and serving (project) all operate
    on the SAME event log and views and share the same team-ownership boundary.
    Splitting them would force inter-service calls and a shared event store
    across service boundaries — violating database-per-service. They live
    behind one boundary; CQRS happens INSIDE this service (write model = event
    log; read models = Redis online + Postgres offline), not across services.

    RPC CATEGORIES:
    DEFINITION (catalog):  DefineFeatureView, GetFeatureView, ListFeatureViews
    WRITE (commands):      WriteFeatures                 → appends events
    READ (projections):    GetOnlineFeatures (latest),
    GetHistoricalFeatures (point-in-time)
    ADMIN (lifecycle):     DeleteFeatureView (soft retire → FeatureViewDeleted),
    RebuildViews (replay log → regenerate projections)

    SERVER-ENFORCED LIMITS (in the CONTRACT, not just prose — see each RPC):
    * page_size (ListFeatureViews, GetHistoricalFeatures): default 20, hard cap
    MAX_PAGE_SIZE = 100 (oversized requests are CLAMPED, not rejected).
    * batch size (entity_ids on GetOnline/GetHistorical; features on Write):
    hard cap MAX_BATCH_SIZE = 1000 entities/rows; OVER-cap requests are
    REJECTED with INVALID_ARGUMENT (a too-large write must fail loudly, not be
    silently truncated — truncation would drop feature rows). proto3 has no
    native numeric bound, so these caps are documented as named constants and
    enforced server-side; the constants are the contract.

    STREAMING CHOICE (interview-critical):
    DATA-PLANE RPCs are UNARY; the long-running ADMIN replay is SERVER-STREAMING.
    - WriteFeatures: producers emit in BATCHES (one RPC = one atomic append
    with one idempotency key). Client-streaming would blur the idempotency/
    atomicity boundary (when is the append "committed"?). Bounded batches +
    idempotency key is simpler and safer.
    - GetOnlineFeatures: a single fast key→value projection read; sub-ms
    budget on the inference hot path — streaming overhead is unwarranted.
    - GetHistoricalFeatures: bounded, PAGINATED point-in-time pulls. Truly
    huge training joins are an offline batch job (export to object storage),
    not a synchronous server stream — a deliberate later refinement.
    - RebuildViews: SERVER-STREAMING — a full log replay runs for minutes, so
    we stream RebuildViewsResponse frames for live feedback and use stream-close as the
    completion signal (no poll loop). Note this is justified by DURATION, not
    data volume — the contrast with the unary reads is the interview point.
    So the only streaming RPC is the admin replay, deliberately, and every choice
    is documented so it is defensible.

    EVENT-SOURCING RECAP (what an interviewer will probe):
    * Source of truth = append-only feature_events log. Views are caches.
    * Reads never replay on the hot path; they read projections.
    * Reproducibility = GetHistoricalFeatures(as_of) over event_time.
    * Recovery = RebuildViews replays the log to rebuild Redis + Postgres views.
    * Soft delete = DeleteFeatureView appends a terminal event; history is kept.
    * Exactly-once EFFECT under retries = idempotency_key on mutating RPCs.
    * Eventual consistency online = surfaced via as_of_version in reads.
    * Async contract = publishes forgepoint.events.v1 FeatureViewDefined /
    FeaturesWritten (canonical, decoupled from this API proto).
    ============================================================================
    """

    @staticmethod
    def DefineFeatureView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.featurestore.v1.FeatureStoreService/DefineFeatureView',
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.DefineFeatureViewRequest.SerializeToString,
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.DefineFeatureViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeatureView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.featurestore.v1.FeatureStoreService/GetFeatureView',
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetFeatureViewRequest.SerializeToString,
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetFeatureViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFeatureViews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.featurestore.v1.FeatureStoreService/ListFeatureViews',
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.ListFeatureViewsRequest.SerializeToString,
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.ListFeatureViewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.featurestore.v1.FeatureStoreService/WriteFeatures',
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.WriteFeaturesRequest.SerializeToString,
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.WriteFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOnlineFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.featurestore.v1.FeatureStoreService/GetOnlineFeatures',
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetOnlineFeaturesRequest.SerializeToString,
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetOnlineFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoricalFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.featurestore.v1.FeatureStoreService/GetHistoricalFeatures',
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetHistoricalFeaturesRequest.SerializeToString,
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.GetHistoricalFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFeatureView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.featurestore.v1.FeatureStoreService/DeleteFeatureView',
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.DeleteFeatureViewRequest.SerializeToString,
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.DeleteFeatureViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RebuildViews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/forgepoint.featurestore.v1.FeatureStoreService/RebuildViews',
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.RebuildViewsRequest.SerializeToString,
            forgepoint_dot_featurestore_dot_v1_dot_featurestore__pb2.RebuildViewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
