# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from forgepoint.inference.v1 import inference_pb2 as forgepoint_dot_inference_dot_v1_dot_inference__pb2


class InferenceGatewayServiceStub:
    """============================================================================
    EVENT PAYLOADS — INTENTIONALLY ABSENT (moved to forgepoint.events.v1)
    ============================================================================

    This proto NO LONGER declares InferenceCompletedEvent / InferenceFailedEvent.
    They are now events.InferenceCompleted / events.InferenceFailed in the
    canonical contract (forgepoint/events/v1/events.proto). The gateway is the
    SOLE producer of the inference event (conflict #1 in events.proto): it is the
    entry point and the only component that knows end-to-end latency, the version
    that ACTUALLY served post traffic-split, the billed principal (api_key_id),
    is_canary, and the token_count Billing meters off ONE event. The canonical
    payload also carries request_id as Model Monitor's ground-truth JOIN KEY and
    keeps the PII discipline (IDs + statistical summaries only — never raw
    tensors, never an end-user identity).

    NOTE — there is NO local FailureReason enum.
    This proto used to declare its own FailureReason. It is GONE: the canonical
    failure taxonomy is events.InferenceFailureReason (in events.proto), and
    this gateway speaks it BOTH on the async bus (events.InferenceFailed.reason)
    AND on the sync surface (BatchPredictResult.failure_reason). Keeping a
    private mirror would have meant two enums that can silently diverge plus an
    error-prone publish-time mapping — for a vocabulary (NO_ROUTE / RATE_LIMITED
    / BULKHEAD_FULL / CIRCUIT_OPEN / UPSTREAM_ERROR / TIMEOUT / INVALID_INPUT /
    QUOTA_EXCEEDED) that Model Monitor and Notification also consume. One enum,
    owned by the event contract, is the right call. The point still
    stands: each value names a resilience pattern firing and maps to a distinct
    operational response (CIRCUIT_OPEN = backend-health; RATE_LIMITED = capacity)
    and to a distinct gRPC status at the edge (NO_ROUTE→NOT_FOUND, RATE_LIMITED /
    BULKHEAD_FULL / QUOTA_EXCEEDED→RESOURCE_EXHAUSTED, CIRCUIT_OPEN /
    UPSTREAM_ERROR→UNAVAILABLE, TIMEOUT→DEADLINE_EXCEEDED, INVALID_INPUT→
    INVALID_ARGUMENT).

    ============================================================================
    INFERENCE GATEWAY SERVICE
    ============================================================================

    WHY one service with both a hot DATA plane (Predict*) and a CONTROL plane
    (route/breaker admin): they're cohesive — the control plane configures
    exactly what the data plane enforces, and both live in the same process that
    holds the in-memory routing table and breaker state. Splitting them would
    force the data plane to fetch routing config over the network on the hot
    path (latency) or duplicate it. Envoy follows the same shape: one proxy
    process, an xDS control surface plus the data path.

    RPC CATEGORIES:
    DATA PLANE (hot path):   Predict, BatchPredict, StreamPredict
    MODEL METADATA (read):   GetModelInfo
    ROUTING CONTROL PLANE:   GetRoute, ListRoutes, UpsertRoute,
    SetTrafficSplit, DeleteRoute
    RESILIENCE OBSERVABILITY: GetCircuitState, ListCircuitStates

    NOTE ON THE EXTERNAL HTTP API: the platform exposes a thin JSON edge that
    maps 1:1 onto these RPCs (gRPC is the canonical internal contract; the HTTP
    adapter converts TensorData bytes ↔ JSON arrays):
    POST /v1/models/{model_name}/predict                      → Predict
    POST /v1/models/{model_name}/versions/{version}/predict   → Predict (the
    {version} path segment becomes version_override, which the edge only
    forwards for callers holding the elevated scope; otherwise 403).
    GET  /v1/models/{model_name}/info                         → GetModelInfo

    AUTH & TENANCY (where the trust boundary is): every RPC runs behind the shared
    auth interceptor (ValidateToken + CheckPermission). The caller's api_key_id,
    team, and scopes are taken FROM THE VERIFIED TOKEN — never from request
    fields. That is why no *Request here carries an api_key/team/owner: a
    client-supplied principal would be account-takeover-for-billing (the inference
    event meters against api_key_id). Data-plane calls require an inference scope;
    control-plane RPCs require an elevated deploy/admin scope (only operators and
    the canary executor reshape routes); version_override on Predict requires that
    same elevation. The pre-flight quota check keys off the token's team against
    the Redis cache flipped by events.QuotaExceeded — also never a request field.
    ============================================================================
    ----- DATA PLANE -------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/forgepoint.inference.v1.InferenceGatewayService/Predict',
                request_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.PredictRequest.SerializeToString,
                response_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.BatchPredict = channel.unary_unary(
                '/forgepoint.inference.v1.InferenceGatewayService/BatchPredict',
                request_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.BatchPredictRequest.SerializeToString,
                response_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.BatchPredictResponse.FromString,
                _registered_method=True)
        self.StreamPredict = channel.unary_stream(
                '/forgepoint.inference.v1.InferenceGatewayService/StreamPredict',
                request_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.StreamPredictRequest.SerializeToString,
                response_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.StreamPredictResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/forgepoint.inference.v1.InferenceGatewayService/GetModelInfo',
                request_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetModelInfoRequest.SerializeToString,
                response_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetModelInfoResponse.FromString,
                _registered_method=True)
        self.GetRoute = channel.unary_unary(
                '/forgepoint.inference.v1.InferenceGatewayService/GetRoute',
                request_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetRouteRequest.SerializeToString,
                response_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetRouteResponse.FromString,
                _registered_method=True)
        self.ListRoutes = channel.unary_unary(
                '/forgepoint.inference.v1.InferenceGatewayService/ListRoutes',
                request_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.ListRoutesRequest.SerializeToString,
                response_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.ListRoutesResponse.FromString,
                _registered_method=True)
        self.UpsertRoute = channel.unary_unary(
                '/forgepoint.inference.v1.InferenceGatewayService/UpsertRoute',
                request_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.UpsertRouteRequest.SerializeToString,
                response_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.UpsertRouteResponse.FromString,
                _registered_method=True)
        self.SetTrafficSplit = channel.unary_unary(
                '/forgepoint.inference.v1.InferenceGatewayService/SetTrafficSplit',
                request_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.SetTrafficSplitRequest.SerializeToString,
                response_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.SetTrafficSplitResponse.FromString,
                _registered_method=True)
        self.DeleteRoute = channel.unary_unary(
                '/forgepoint.inference.v1.InferenceGatewayService/DeleteRoute',
                request_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.DeleteRouteRequest.SerializeToString,
                response_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.DeleteRouteResponse.FromString,
                _registered_method=True)
        self.GetCircuitState = channel.unary_unary(
                '/forgepoint.inference.v1.InferenceGatewayService/GetCircuitState',
                request_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetCircuitStateRequest.SerializeToString,
                response_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetCircuitStateResponse.FromString,
                _registered_method=True)
        self.ListCircuitStates = channel.unary_unary(
                '/forgepoint.inference.v1.InferenceGatewayService/ListCircuitStates',
                request_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.ListCircuitStatesRequest.SerializeToString,
                response_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.ListCircuitStatesResponse.FromString,
                _registered_method=True)


class InferenceGatewayServiceServicer:
    """============================================================================
    EVENT PAYLOADS — INTENTIONALLY ABSENT (moved to forgepoint.events.v1)
    ============================================================================

    This proto NO LONGER declares InferenceCompletedEvent / InferenceFailedEvent.
    They are now events.InferenceCompleted / events.InferenceFailed in the
    canonical contract (forgepoint/events/v1/events.proto). The gateway is the
    SOLE producer of the inference event (conflict #1 in events.proto): it is the
    entry point and the only component that knows end-to-end latency, the version
    that ACTUALLY served post traffic-split, the billed principal (api_key_id),
    is_canary, and the token_count Billing meters off ONE event. The canonical
    payload also carries request_id as Model Monitor's ground-truth JOIN KEY and
    keeps the PII discipline (IDs + statistical summaries only — never raw
    tensors, never an end-user identity).

    NOTE — there is NO local FailureReason enum.
    This proto used to declare its own FailureReason. It is GONE: the canonical
    failure taxonomy is events.InferenceFailureReason (in events.proto), and
    this gateway speaks it BOTH on the async bus (events.InferenceFailed.reason)
    AND on the sync surface (BatchPredictResult.failure_reason). Keeping a
    private mirror would have meant two enums that can silently diverge plus an
    error-prone publish-time mapping — for a vocabulary (NO_ROUTE / RATE_LIMITED
    / BULKHEAD_FULL / CIRCUIT_OPEN / UPSTREAM_ERROR / TIMEOUT / INVALID_INPUT /
    QUOTA_EXCEEDED) that Model Monitor and Notification also consume. One enum,
    owned by the event contract, is the right call. The point still
    stands: each value names a resilience pattern firing and maps to a distinct
    operational response (CIRCUIT_OPEN = backend-health; RATE_LIMITED = capacity)
    and to a distinct gRPC status at the edge (NO_ROUTE→NOT_FOUND, RATE_LIMITED /
    BULKHEAD_FULL / QUOTA_EXCEEDED→RESOURCE_EXHAUSTED, CIRCUIT_OPEN /
    UPSTREAM_ERROR→UNAVAILABLE, TIMEOUT→DEADLINE_EXCEEDED, INVALID_INPUT→
    INVALID_ARGUMENT).

    ============================================================================
    INFERENCE GATEWAY SERVICE
    ============================================================================

    WHY one service with both a hot DATA plane (Predict*) and a CONTROL plane
    (route/breaker admin): they're cohesive — the control plane configures
    exactly what the data plane enforces, and both live in the same process that
    holds the in-memory routing table and breaker state. Splitting them would
    force the data plane to fetch routing config over the network on the hot
    path (latency) or duplicate it. Envoy follows the same shape: one proxy
    process, an xDS control surface plus the data path.

    RPC CATEGORIES:
    DATA PLANE (hot path):   Predict, BatchPredict, StreamPredict
    MODEL METADATA (read):   GetModelInfo
    ROUTING CONTROL PLANE:   GetRoute, ListRoutes, UpsertRoute,
    SetTrafficSplit, DeleteRoute
    RESILIENCE OBSERVABILITY: GetCircuitState, ListCircuitStates

    NOTE ON THE EXTERNAL HTTP API: the platform exposes a thin JSON edge that
    maps 1:1 onto these RPCs (gRPC is the canonical internal contract; the HTTP
    adapter converts TensorData bytes ↔ JSON arrays):
    POST /v1/models/{model_name}/predict                      → Predict
    POST /v1/models/{model_name}/versions/{version}/predict   → Predict (the
    {version} path segment becomes version_override, which the edge only
    forwards for callers holding the elevated scope; otherwise 403).
    GET  /v1/models/{model_name}/info                         → GetModelInfo

    AUTH & TENANCY (where the trust boundary is): every RPC runs behind the shared
    auth interceptor (ValidateToken + CheckPermission). The caller's api_key_id,
    team, and scopes are taken FROM THE VERIFIED TOKEN — never from request
    fields. That is why no *Request here carries an api_key/team/owner: a
    client-supplied principal would be account-takeover-for-billing (the inference
    event meters against api_key_id). Data-plane calls require an inference scope;
    control-plane RPCs require an elevated deploy/admin scope (only operators and
    the canary executor reshape routes); version_override on Predict requires that
    same elevation. The pre-flight quota check keys off the token's team against
    the Redis cache flipped by events.QuotaExceeded — also never a request field.
    ============================================================================
    ----- DATA PLANE -------------------------------------------------------
    """

    def Predict(self, request, context):
        """Predict routes a single inference request to a model-serving backend via
        the full resilience stack (rate limit → route → traffic split → circuit
        breaker → bulkhead → forward with retry) and returns the outputs plus the
        version that served and the latency observed. Emits InferenceCompleted on
        success / InferenceFailed on failure (async, off the response path).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchPredict(self, request, context):
        """BatchPredict scores many inputs for one model in a single request,
        returning one result per item with PARTIAL-SUCCESS semantics (a bad item
        doesn't fail the batch). Use for BOUNDED batches (capped at 256 items
        server-side); for large/unbounded batches use StreamPredict.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPredict(self, request, context):
        """StreamPredict scores a (potentially large) batch and SERVER-STREAMS one
        result per item as each completes — incremental delivery with bounded
        gateway RESPONSE memory (it never buffers the whole result set). The single
        request carries all items (capped at 10000 server-side — the request list is
        still buffered in full, so it is bounded too); results flow back until the
        stream ends. Choose this over BatchPredict when the batch is large or you
        want to start consuming results before the batch finishes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """----- MODEL METADATA (read) -------------------------------------------

        GetModelInfo returns the client-facing metadata a caller needs to construct
        a valid predict request WITHOUT knowing internal versions: the input/output
        tensor schema (names/shapes/dtypes for edge validation), the currently
        routable versions and their traffic weights, and whether the model is
        serving at all. Backs the external GET /v1/models/{model_name}/info. WHY a
        dedicated read RPC and not "just call GetRoute": GetRoute is the OPERATOR
        view (raw routing table, elevated scope); GetModelInfo is the CALLER view
        (the public contract of the model, inference scope) and deliberately omits
        server-internal fields like backend endpoints and breaker internals.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoute(self, request, context):
        """----- ROUTING CONTROL PLANE -------------------------------------------

        GetRoute returns the current routing-table entry (versions + weights) for
        one model. Read-only; used by operators, the UI, and the canary executor
        to inspect current splits.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRoutes(self, request, context):
        """ListRoutes returns the whole routing table, paginated (page_size capped at
        100 server-side). For the operator dashboard / `fp` CLI.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertRoute(self, request, context):
        """UpsertRoute creates or replaces a model's route (break-glass manual
        control; routes are normally driven by ModelDeployed events). Endpoints
        are server-resolved (never accepted from the client) and weights must sum
        to 10000. Requires elevated permission. Idempotent via idempotency_key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTrafficSplit(self, request, context):
        """SetTrafficSplit adjusts ONLY the version weights of an existing route —
        the canary dial (e.g., 90/10 → 50/50 → 0/100). The most common rollout
        operation; narrow and audit-friendly by design. Requires elevated
        permission. Idempotent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRoute(self, request, context):
        """DeleteRoute removes a model from routing entirely (subsequent predicts get
        NOT_FOUND). Normally driven by ModelUndeployed; this is the override.
        Requires elevated permission. Idempotent (deleting twice is a no-op).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCircuitState(self, request, context):
        """----- RESILIENCE OBSERVABILITY ----------------------------------------

        GetCircuitState reports the breaker state for one backend (model+version):
        CLOSED / OPEN / HALF_OPEN plus failure count and last transition. Turns
        an invisible failure mode into an observable one for dashboards/operators.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCircuitStates(self, request, context):
        """ListCircuitStates lists breaker states across backends (optional model
        filter), paginated — the at-a-glance health view of all routed backends.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.PredictRequest.FromString,
                    response_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.PredictResponse.SerializeToString,
            ),
            'BatchPredict': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchPredict,
                    request_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.BatchPredictRequest.FromString,
                    response_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.BatchPredictResponse.SerializeToString,
            ),
            'StreamPredict': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPredict,
                    request_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.StreamPredictRequest.FromString,
                    response_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.StreamPredictResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetModelInfoRequest.FromString,
                    response_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetModelInfoResponse.SerializeToString,
            ),
            'GetRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoute,
                    request_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetRouteRequest.FromString,
                    response_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetRouteResponse.SerializeToString,
            ),
            'ListRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRoutes,
                    request_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.ListRoutesRequest.FromString,
                    response_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.ListRoutesResponse.SerializeToString,
            ),
            'UpsertRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertRoute,
                    request_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.UpsertRouteRequest.FromString,
                    response_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.UpsertRouteResponse.SerializeToString,
            ),
            'SetTrafficSplit': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTrafficSplit,
                    request_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.SetTrafficSplitRequest.FromString,
                    response_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.SetTrafficSplitResponse.SerializeToString,
            ),
            'DeleteRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRoute,
                    request_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.DeleteRouteRequest.FromString,
                    response_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.DeleteRouteResponse.SerializeToString,
            ),
            'GetCircuitState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCircuitState,
                    request_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetCircuitStateRequest.FromString,
                    response_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetCircuitStateResponse.SerializeToString,
            ),
            'ListCircuitStates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCircuitStates,
                    request_deserializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.ListCircuitStatesRequest.FromString,
                    response_serializer=forgepoint_dot_inference_dot_v1_dot_inference__pb2.ListCircuitStatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forgepoint.inference.v1.InferenceGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forgepoint.inference.v1.InferenceGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceGatewayService:
    """============================================================================
    EVENT PAYLOADS — INTENTIONALLY ABSENT (moved to forgepoint.events.v1)
    ============================================================================

    This proto NO LONGER declares InferenceCompletedEvent / InferenceFailedEvent.
    They are now events.InferenceCompleted / events.InferenceFailed in the
    canonical contract (forgepoint/events/v1/events.proto). The gateway is the
    SOLE producer of the inference event (conflict #1 in events.proto): it is the
    entry point and the only component that knows end-to-end latency, the version
    that ACTUALLY served post traffic-split, the billed principal (api_key_id),
    is_canary, and the token_count Billing meters off ONE event. The canonical
    payload also carries request_id as Model Monitor's ground-truth JOIN KEY and
    keeps the PII discipline (IDs + statistical summaries only — never raw
    tensors, never an end-user identity).

    NOTE — there is NO local FailureReason enum.
    This proto used to declare its own FailureReason. It is GONE: the canonical
    failure taxonomy is events.InferenceFailureReason (in events.proto), and
    this gateway speaks it BOTH on the async bus (events.InferenceFailed.reason)
    AND on the sync surface (BatchPredictResult.failure_reason). Keeping a
    private mirror would have meant two enums that can silently diverge plus an
    error-prone publish-time mapping — for a vocabulary (NO_ROUTE / RATE_LIMITED
    / BULKHEAD_FULL / CIRCUIT_OPEN / UPSTREAM_ERROR / TIMEOUT / INVALID_INPUT /
    QUOTA_EXCEEDED) that Model Monitor and Notification also consume. One enum,
    owned by the event contract, is the right call. The point still
    stands: each value names a resilience pattern firing and maps to a distinct
    operational response (CIRCUIT_OPEN = backend-health; RATE_LIMITED = capacity)
    and to a distinct gRPC status at the edge (NO_ROUTE→NOT_FOUND, RATE_LIMITED /
    BULKHEAD_FULL / QUOTA_EXCEEDED→RESOURCE_EXHAUSTED, CIRCUIT_OPEN /
    UPSTREAM_ERROR→UNAVAILABLE, TIMEOUT→DEADLINE_EXCEEDED, INVALID_INPUT→
    INVALID_ARGUMENT).

    ============================================================================
    INFERENCE GATEWAY SERVICE
    ============================================================================

    WHY one service with both a hot DATA plane (Predict*) and a CONTROL plane
    (route/breaker admin): they're cohesive — the control plane configures
    exactly what the data plane enforces, and both live in the same process that
    holds the in-memory routing table and breaker state. Splitting them would
    force the data plane to fetch routing config over the network on the hot
    path (latency) or duplicate it. Envoy follows the same shape: one proxy
    process, an xDS control surface plus the data path.

    RPC CATEGORIES:
    DATA PLANE (hot path):   Predict, BatchPredict, StreamPredict
    MODEL METADATA (read):   GetModelInfo
    ROUTING CONTROL PLANE:   GetRoute, ListRoutes, UpsertRoute,
    SetTrafficSplit, DeleteRoute
    RESILIENCE OBSERVABILITY: GetCircuitState, ListCircuitStates

    NOTE ON THE EXTERNAL HTTP API: the platform exposes a thin JSON edge that
    maps 1:1 onto these RPCs (gRPC is the canonical internal contract; the HTTP
    adapter converts TensorData bytes ↔ JSON arrays):
    POST /v1/models/{model_name}/predict                      → Predict
    POST /v1/models/{model_name}/versions/{version}/predict   → Predict (the
    {version} path segment becomes version_override, which the edge only
    forwards for callers holding the elevated scope; otherwise 403).
    GET  /v1/models/{model_name}/info                         → GetModelInfo

    AUTH & TENANCY (where the trust boundary is): every RPC runs behind the shared
    auth interceptor (ValidateToken + CheckPermission). The caller's api_key_id,
    team, and scopes are taken FROM THE VERIFIED TOKEN — never from request
    fields. That is why no *Request here carries an api_key/team/owner: a
    client-supplied principal would be account-takeover-for-billing (the inference
    event meters against api_key_id). Data-plane calls require an inference scope;
    control-plane RPCs require an elevated deploy/admin scope (only operators and
    the canary executor reshape routes); version_override on Predict requires that
    same elevation. The pre-flight quota check keys off the token's team against
    the Redis cache flipped by events.QuotaExceeded — also never a request field.
    ============================================================================
    ----- DATA PLANE -------------------------------------------------------
    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.inference.v1.InferenceGatewayService/Predict',
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.PredictRequest.SerializeToString,
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchPredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.inference.v1.InferenceGatewayService/BatchPredict',
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.BatchPredictRequest.SerializeToString,
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.BatchPredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/forgepoint.inference.v1.InferenceGatewayService/StreamPredict',
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.StreamPredictRequest.SerializeToString,
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.StreamPredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.inference.v1.InferenceGatewayService/GetModelInfo',
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetModelInfoRequest.SerializeToString,
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.inference.v1.InferenceGatewayService/GetRoute',
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetRouteRequest.SerializeToString,
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.inference.v1.InferenceGatewayService/ListRoutes',
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.ListRoutesRequest.SerializeToString,
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.ListRoutesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.inference.v1.InferenceGatewayService/UpsertRoute',
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.UpsertRouteRequest.SerializeToString,
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.UpsertRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTrafficSplit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.inference.v1.InferenceGatewayService/SetTrafficSplit',
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.SetTrafficSplitRequest.SerializeToString,
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.SetTrafficSplitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.inference.v1.InferenceGatewayService/DeleteRoute',
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.DeleteRouteRequest.SerializeToString,
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.DeleteRouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCircuitState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.inference.v1.InferenceGatewayService/GetCircuitState',
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetCircuitStateRequest.SerializeToString,
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.GetCircuitStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCircuitStates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.inference.v1.InferenceGatewayService/ListCircuitStates',
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.ListCircuitStatesRequest.SerializeToString,
            forgepoint_dot_inference_dot_v1_dot_inference__pb2.ListCircuitStatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
