# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from forgepoint.monitor.v1 import monitor_pb2 as forgepoint_dot_monitor_dot_v1_dot_monitor__pb2


class MonitorServiceStub:
    """============================================================================
    EVENT CONTRACT  (this service's NATS surface — payloads live in events.proto)
    ============================================================================

    This service does NOT define any event-payload messages. Every NATS payload it
    produces or consumes is owned by the canonical forgepoint.events.v1 contract
    (imported above). WHY: events are a PUBLISHED, versioned contract shared by
    BOTH ends of every pipe — if Model Monitor redefined ModelDriftDetected here,
    it would diverge from what Notification/Experiment-Tracker/Orchestrator compile
    against, which is exactly the incoherence the events package was created to
    fix. The handler maps this service's domain enums to/from the event enums at
    the publish/consume boundary (a few lines of mechanical conversion).

    PRODUCES (1):
    fp.models.drift.detected → events.ModelDriftDetected   THE LOOP-CLOSER.
    Emitted once per drift report (idempotent on window_id; consumers dedupe on
    EventEnvelope.id, with report_id as a second business handle). Consumed by
    notification (alert), experiment-tracker (record), pipeline-orchestrator
    (on CRITICAL + auto_retrain → TriggerExecution of the retrain pipeline).
    EventEnvelope.source = "model-monitor" records the real producer even
    though the subject lives under fp.models.* (ownership-by-RESOURCE: the
    event is about a MODEL). The canonical message is FAT-BUT-FLAT — headline
    scalars (model_name/model_version/drift_type/severity) + report_id +
    repeated DriftMetric breakdown + the closed-loop control fields
    (auto_retrain/retrain_pipeline_id/retrain_context as a Struct) — so the
    orchestrator closes the loop with NO callback into this service. It embeds
    NO monitor.DriftReport: the report is flattened into the event (decoupling).

    FIELD-MAPPING (monitor domain → events.ModelDriftDetected), done in the handler:
    DriftReport.model_name        → model_name
    DriftReport.model_version     → model_version
    DriftReport.drift_type        → drift_type   (monitor.DriftType  → events.DriftType)
    DriftReport.severity          → severity     (monitor.DriftSeverity → events.DriftSeverity)
    DriftReport.id                → report_id
    DriftReport.metrics[]         → metrics[]     (monitor.DriftMetric → events.DriftMetric,
    incl. monitor.DriftMethod → events.DriftMethod)
    DriftReport.window_start/end  → window_start/window_end
    DriftReport.sample_count      → sample_count
    Monitor.auto_retrain          → auto_retrain
    Monitor.retrain_pipeline_id   → retrain_pipeline_id
    (computed drift summary)      → retrain_context (Struct; small, PII-free)
    DriftReport.created_at        → detected_at
    The three mirror enums (DriftType/DriftMethod/DriftSeverity) have IDENTICAL
    value numbering on both sides, so the conversion is a cast — but it MUST go
    through an explicit switch (not an unchecked numeric cast) so a future
    divergence is caught at the boundary, not silently mis-serialized.

    CONSUMES (3) — these drive the streaming-aggregation loop; none is an RPC:
    fp.inference.completed → events.InferenceCompleted   THE PRIMARY INPUT.
    Folded into the per-model sliding window: feature_summary → DATA-drift math,
    prediction_summary → PREDICTION-drift math, latency → a performance signal.
    request_id is the GROUND-TRUTH JOIN KEY — the monitor records the
    request_ids it observed so a later SubmitGroundTruth can match delayed
    labels back by request_id. version is captured here so a report is tied to
    the exact served version (vital under canary splitting).
    fp.features.written    → events.FeaturesWritten
    Scopes drift checks / invalidates baseline caches for the changed entities.
    fp.models.promoted     → events.ModelPromoted
    On to_stage == PRODUCTION, RESET the drift baseline to the new prod
    version's training distribution (else every new deploy reads as drift vs a
    stale baseline). The single-production invariant on this event also tells
    the monitor which version to start scoring.
    (fp.inference.failed → events.InferenceFailed is an OPTIONAL future input for
    an error-RATE degradation signal; not consumed in this phase, noted for the
    reader so the contract is complete.)
    ============================================================================

    ============================================================================
    MODEL MONITOR SERVICE
    ============================================================================

    WHY a single MonitorService (not split Config/Report/Stream services): the
    config, the reports it produces, and the live stream are one cohesive bounded
    context — "the drift monitoring of models". Splitting them would force
    inter-service calls for flows that are naturally one boundary (configuring a
    monitor and reading its reports). One service, one Postgres+Redis store.

    NOTE ON THE CONTROL LOOP: the most important behavior — consuming
    `fp.inference.completed`, windowing, scoring, and firing the retrain — is NOT
    an RPC. It is an event-driven loop running inside the service (NATS consumer +
    scorer + policy). This gRPC surface is the CONTROL & OBSERVABILITY plane over
    that loop: configure it, read what it found, watch it live, feed it truth.

    RPC CATEGORIES:
    CONFIG:        ConfigureMonitor, DeleteMonitor, ResetBaseline
    OBSERVABILITY: GetModelHealth, GetMonitorStatus, ListMonitors,
    GetDriftReport, ListDriftReports, StreamDriftEvents
    FEEDBACK:      SubmitGroundTruth (delayed labels → performance decay)

    AUTH: every RPC is guarded by the shared auth interceptor (see auth.proto).
    Drift scores and config are operationally sensitive; reads require monitoring
    read scope, writes (ConfigureMonitor, DeleteMonitor, ResetBaseline,
    SubmitGroundTruth) require write scope. EVERY RPC is additionally TEAM-SCOPED
    by the interceptor from the caller's auth claims — no request carries a team or
    tenancy field (those would be cross-tenant footguns; see per-request notes).
    ============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConfigureMonitor = channel.unary_unary(
                '/forgepoint.monitor.v1.MonitorService/ConfigureMonitor',
                request_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ConfigureMonitorRequest.SerializeToString,
                response_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ConfigureMonitorResponse.FromString,
                _registered_method=True)
        self.DeleteMonitor = channel.unary_unary(
                '/forgepoint.monitor.v1.MonitorService/DeleteMonitor',
                request_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.DeleteMonitorRequest.SerializeToString,
                response_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.DeleteMonitorResponse.FromString,
                _registered_method=True)
        self.ResetBaseline = channel.unary_unary(
                '/forgepoint.monitor.v1.MonitorService/ResetBaseline',
                request_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ResetBaselineRequest.SerializeToString,
                response_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ResetBaselineResponse.FromString,
                _registered_method=True)
        self.GetModelHealth = channel.unary_unary(
                '/forgepoint.monitor.v1.MonitorService/GetModelHealth',
                request_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetModelHealthRequest.SerializeToString,
                response_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetModelHealthResponse.FromString,
                _registered_method=True)
        self.GetMonitorStatus = channel.unary_unary(
                '/forgepoint.monitor.v1.MonitorService/GetMonitorStatus',
                request_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetMonitorStatusRequest.SerializeToString,
                response_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetMonitorStatusResponse.FromString,
                _registered_method=True)
        self.ListMonitors = channel.unary_unary(
                '/forgepoint.monitor.v1.MonitorService/ListMonitors',
                request_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ListMonitorsRequest.SerializeToString,
                response_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ListMonitorsResponse.FromString,
                _registered_method=True)
        self.GetDriftReport = channel.unary_unary(
                '/forgepoint.monitor.v1.MonitorService/GetDriftReport',
                request_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetDriftReportRequest.SerializeToString,
                response_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetDriftReportResponse.FromString,
                _registered_method=True)
        self.ListDriftReports = channel.unary_unary(
                '/forgepoint.monitor.v1.MonitorService/ListDriftReports',
                request_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ListDriftReportsRequest.SerializeToString,
                response_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ListDriftReportsResponse.FromString,
                _registered_method=True)
        self.SubmitGroundTruth = channel.unary_unary(
                '/forgepoint.monitor.v1.MonitorService/SubmitGroundTruth',
                request_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.SubmitGroundTruthRequest.SerializeToString,
                response_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.SubmitGroundTruthResponse.FromString,
                _registered_method=True)
        self.StreamDriftEvents = channel.unary_stream(
                '/forgepoint.monitor.v1.MonitorService/StreamDriftEvents',
                request_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.StreamDriftEventsRequest.SerializeToString,
                response_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.StreamDriftEventsResponse.FromString,
                _registered_method=True)


class MonitorServiceServicer:
    """============================================================================
    EVENT CONTRACT  (this service's NATS surface — payloads live in events.proto)
    ============================================================================

    This service does NOT define any event-payload messages. Every NATS payload it
    produces or consumes is owned by the canonical forgepoint.events.v1 contract
    (imported above). WHY: events are a PUBLISHED, versioned contract shared by
    BOTH ends of every pipe — if Model Monitor redefined ModelDriftDetected here,
    it would diverge from what Notification/Experiment-Tracker/Orchestrator compile
    against, which is exactly the incoherence the events package was created to
    fix. The handler maps this service's domain enums to/from the event enums at
    the publish/consume boundary (a few lines of mechanical conversion).

    PRODUCES (1):
    fp.models.drift.detected → events.ModelDriftDetected   THE LOOP-CLOSER.
    Emitted once per drift report (idempotent on window_id; consumers dedupe on
    EventEnvelope.id, with report_id as a second business handle). Consumed by
    notification (alert), experiment-tracker (record), pipeline-orchestrator
    (on CRITICAL + auto_retrain → TriggerExecution of the retrain pipeline).
    EventEnvelope.source = "model-monitor" records the real producer even
    though the subject lives under fp.models.* (ownership-by-RESOURCE: the
    event is about a MODEL). The canonical message is FAT-BUT-FLAT — headline
    scalars (model_name/model_version/drift_type/severity) + report_id +
    repeated DriftMetric breakdown + the closed-loop control fields
    (auto_retrain/retrain_pipeline_id/retrain_context as a Struct) — so the
    orchestrator closes the loop with NO callback into this service. It embeds
    NO monitor.DriftReport: the report is flattened into the event (decoupling).

    FIELD-MAPPING (monitor domain → events.ModelDriftDetected), done in the handler:
    DriftReport.model_name        → model_name
    DriftReport.model_version     → model_version
    DriftReport.drift_type        → drift_type   (monitor.DriftType  → events.DriftType)
    DriftReport.severity          → severity     (monitor.DriftSeverity → events.DriftSeverity)
    DriftReport.id                → report_id
    DriftReport.metrics[]         → metrics[]     (monitor.DriftMetric → events.DriftMetric,
    incl. monitor.DriftMethod → events.DriftMethod)
    DriftReport.window_start/end  → window_start/window_end
    DriftReport.sample_count      → sample_count
    Monitor.auto_retrain          → auto_retrain
    Monitor.retrain_pipeline_id   → retrain_pipeline_id
    (computed drift summary)      → retrain_context (Struct; small, PII-free)
    DriftReport.created_at        → detected_at
    The three mirror enums (DriftType/DriftMethod/DriftSeverity) have IDENTICAL
    value numbering on both sides, so the conversion is a cast — but it MUST go
    through an explicit switch (not an unchecked numeric cast) so a future
    divergence is caught at the boundary, not silently mis-serialized.

    CONSUMES (3) — these drive the streaming-aggregation loop; none is an RPC:
    fp.inference.completed → events.InferenceCompleted   THE PRIMARY INPUT.
    Folded into the per-model sliding window: feature_summary → DATA-drift math,
    prediction_summary → PREDICTION-drift math, latency → a performance signal.
    request_id is the GROUND-TRUTH JOIN KEY — the monitor records the
    request_ids it observed so a later SubmitGroundTruth can match delayed
    labels back by request_id. version is captured here so a report is tied to
    the exact served version (vital under canary splitting).
    fp.features.written    → events.FeaturesWritten
    Scopes drift checks / invalidates baseline caches for the changed entities.
    fp.models.promoted     → events.ModelPromoted
    On to_stage == PRODUCTION, RESET the drift baseline to the new prod
    version's training distribution (else every new deploy reads as drift vs a
    stale baseline). The single-production invariant on this event also tells
    the monitor which version to start scoring.
    (fp.inference.failed → events.InferenceFailed is an OPTIONAL future input for
    an error-RATE degradation signal; not consumed in this phase, noted for the
    reader so the contract is complete.)
    ============================================================================

    ============================================================================
    MODEL MONITOR SERVICE
    ============================================================================

    WHY a single MonitorService (not split Config/Report/Stream services): the
    config, the reports it produces, and the live stream are one cohesive bounded
    context — "the drift monitoring of models". Splitting them would force
    inter-service calls for flows that are naturally one boundary (configuring a
    monitor and reading its reports). One service, one Postgres+Redis store.

    NOTE ON THE CONTROL LOOP: the most important behavior — consuming
    `fp.inference.completed`, windowing, scoring, and firing the retrain — is NOT
    an RPC. It is an event-driven loop running inside the service (NATS consumer +
    scorer + policy). This gRPC surface is the CONTROL & OBSERVABILITY plane over
    that loop: configure it, read what it found, watch it live, feed it truth.

    RPC CATEGORIES:
    CONFIG:        ConfigureMonitor, DeleteMonitor, ResetBaseline
    OBSERVABILITY: GetModelHealth, GetMonitorStatus, ListMonitors,
    GetDriftReport, ListDriftReports, StreamDriftEvents
    FEEDBACK:      SubmitGroundTruth (delayed labels → performance decay)

    AUTH: every RPC is guarded by the shared auth interceptor (see auth.proto).
    Drift scores and config are operationally sensitive; reads require monitoring
    read scope, writes (ConfigureMonitor, DeleteMonitor, ResetBaseline,
    SubmitGroundTruth) require write scope. EVERY RPC is additionally TEAM-SCOPED
    by the interceptor from the caller's auth claims — no request carries a team or
    tenancy field (those would be cross-tenant footguns; see per-request notes).
    ============================================================================
    """

    def ConfigureMonitor(self, request, context):
        """ConfigureMonitor upserts a model's monitor: window shape, per-drift-type
        thresholds, and the auto-retrain switch. The ONLY config write path.
        SERVER-authoritative fields (id, owner_team, state, baseline_*) are not
        accepted here (mass-assignment guard).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMonitor(self, request, context):
        """DeleteMonitor stops monitoring a model (soft-delete by default; optionally
        purges drift history). Idempotent on idempotency_key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetBaseline(self, request, context):
        """ResetBaseline manually re-pins the drift baseline to a model version's
        training distribution (operator escape hatch; auto-reset happens on
        ModelPromoted). The baseline is server-resolved from the named version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelHealth(self, request, context):
        """GetModelHealth returns the at-a-glance health verdict for one model (overall
        severity + per-type lights + state). The one-line "is this model healthy?"
        read for dashboards and `fp monitor <model>`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMonitorStatus(self, request, context):
        """GetMonitorStatus returns the live status for a model: lifecycle state,
        current-window fill, the latest report, and lifetime drift count. The
        operator drill-in view (hits the live Redis window).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMonitors(self, request, context):
        """ListMonitors returns the caller team's monitored-model FLEET (config + current
        health per row), paginated, with optional severity/state filters. Powers the
        Web UI monitoring table and `fp monitor` (no arg). Page size capped at 100.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDriftReport(self, request, context):
        """GetDriftReport fetches a single persisted drift report by id (the handle the
        ModelDriftDetected event and UI deep-links reference).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDriftReports(self, request, context):
        """ListDriftReports returns a model's drift history (newest first), paginated,
        with optional severity and time-range filters. Page size is capped server-
        side at 100.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitGroundTruth(self, request, context):
        """SubmitGroundTruth backfills delayed true outcomes (batched) so the monitor
        can compute PERFORMANCE DECAY — the lagging, ground-truth confirmation of
        drift. Returns how many labels matched an observed prediction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDriftEvents(self, request, context):
        """StreamDriftEvents opens a long-lived SERVER-STREAM of drift events as they
        fire, optionally filtered by model and min severity. Powers live dashboards
        and `fp monitor --watch` without polling. (Server-streaming: one request,
        many responses, until the client cancels or the deadline elapses.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConfigureMonitor': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureMonitor,
                    request_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ConfigureMonitorRequest.FromString,
                    response_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ConfigureMonitorResponse.SerializeToString,
            ),
            'DeleteMonitor': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMonitor,
                    request_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.DeleteMonitorRequest.FromString,
                    response_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.DeleteMonitorResponse.SerializeToString,
            ),
            'ResetBaseline': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetBaseline,
                    request_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ResetBaselineRequest.FromString,
                    response_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ResetBaselineResponse.SerializeToString,
            ),
            'GetModelHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelHealth,
                    request_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetModelHealthRequest.FromString,
                    response_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetModelHealthResponse.SerializeToString,
            ),
            'GetMonitorStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMonitorStatus,
                    request_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetMonitorStatusRequest.FromString,
                    response_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetMonitorStatusResponse.SerializeToString,
            ),
            'ListMonitors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMonitors,
                    request_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ListMonitorsRequest.FromString,
                    response_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ListMonitorsResponse.SerializeToString,
            ),
            'GetDriftReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDriftReport,
                    request_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetDriftReportRequest.FromString,
                    response_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetDriftReportResponse.SerializeToString,
            ),
            'ListDriftReports': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDriftReports,
                    request_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ListDriftReportsRequest.FromString,
                    response_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ListDriftReportsResponse.SerializeToString,
            ),
            'SubmitGroundTruth': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitGroundTruth,
                    request_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.SubmitGroundTruthRequest.FromString,
                    response_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.SubmitGroundTruthResponse.SerializeToString,
            ),
            'StreamDriftEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamDriftEvents,
                    request_deserializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.StreamDriftEventsRequest.FromString,
                    response_serializer=forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.StreamDriftEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forgepoint.monitor.v1.MonitorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forgepoint.monitor.v1.MonitorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MonitorService:
    """============================================================================
    EVENT CONTRACT  (this service's NATS surface — payloads live in events.proto)
    ============================================================================

    This service does NOT define any event-payload messages. Every NATS payload it
    produces or consumes is owned by the canonical forgepoint.events.v1 contract
    (imported above). WHY: events are a PUBLISHED, versioned contract shared by
    BOTH ends of every pipe — if Model Monitor redefined ModelDriftDetected here,
    it would diverge from what Notification/Experiment-Tracker/Orchestrator compile
    against, which is exactly the incoherence the events package was created to
    fix. The handler maps this service's domain enums to/from the event enums at
    the publish/consume boundary (a few lines of mechanical conversion).

    PRODUCES (1):
    fp.models.drift.detected → events.ModelDriftDetected   THE LOOP-CLOSER.
    Emitted once per drift report (idempotent on window_id; consumers dedupe on
    EventEnvelope.id, with report_id as a second business handle). Consumed by
    notification (alert), experiment-tracker (record), pipeline-orchestrator
    (on CRITICAL + auto_retrain → TriggerExecution of the retrain pipeline).
    EventEnvelope.source = "model-monitor" records the real producer even
    though the subject lives under fp.models.* (ownership-by-RESOURCE: the
    event is about a MODEL). The canonical message is FAT-BUT-FLAT — headline
    scalars (model_name/model_version/drift_type/severity) + report_id +
    repeated DriftMetric breakdown + the closed-loop control fields
    (auto_retrain/retrain_pipeline_id/retrain_context as a Struct) — so the
    orchestrator closes the loop with NO callback into this service. It embeds
    NO monitor.DriftReport: the report is flattened into the event (decoupling).

    FIELD-MAPPING (monitor domain → events.ModelDriftDetected), done in the handler:
    DriftReport.model_name        → model_name
    DriftReport.model_version     → model_version
    DriftReport.drift_type        → drift_type   (monitor.DriftType  → events.DriftType)
    DriftReport.severity          → severity     (monitor.DriftSeverity → events.DriftSeverity)
    DriftReport.id                → report_id
    DriftReport.metrics[]         → metrics[]     (monitor.DriftMetric → events.DriftMetric,
    incl. monitor.DriftMethod → events.DriftMethod)
    DriftReport.window_start/end  → window_start/window_end
    DriftReport.sample_count      → sample_count
    Monitor.auto_retrain          → auto_retrain
    Monitor.retrain_pipeline_id   → retrain_pipeline_id
    (computed drift summary)      → retrain_context (Struct; small, PII-free)
    DriftReport.created_at        → detected_at
    The three mirror enums (DriftType/DriftMethod/DriftSeverity) have IDENTICAL
    value numbering on both sides, so the conversion is a cast — but it MUST go
    through an explicit switch (not an unchecked numeric cast) so a future
    divergence is caught at the boundary, not silently mis-serialized.

    CONSUMES (3) — these drive the streaming-aggregation loop; none is an RPC:
    fp.inference.completed → events.InferenceCompleted   THE PRIMARY INPUT.
    Folded into the per-model sliding window: feature_summary → DATA-drift math,
    prediction_summary → PREDICTION-drift math, latency → a performance signal.
    request_id is the GROUND-TRUTH JOIN KEY — the monitor records the
    request_ids it observed so a later SubmitGroundTruth can match delayed
    labels back by request_id. version is captured here so a report is tied to
    the exact served version (vital under canary splitting).
    fp.features.written    → events.FeaturesWritten
    Scopes drift checks / invalidates baseline caches for the changed entities.
    fp.models.promoted     → events.ModelPromoted
    On to_stage == PRODUCTION, RESET the drift baseline to the new prod
    version's training distribution (else every new deploy reads as drift vs a
    stale baseline). The single-production invariant on this event also tells
    the monitor which version to start scoring.
    (fp.inference.failed → events.InferenceFailed is an OPTIONAL future input for
    an error-RATE degradation signal; not consumed in this phase, noted for the
    reader so the contract is complete.)
    ============================================================================

    ============================================================================
    MODEL MONITOR SERVICE
    ============================================================================

    WHY a single MonitorService (not split Config/Report/Stream services): the
    config, the reports it produces, and the live stream are one cohesive bounded
    context — "the drift monitoring of models". Splitting them would force
    inter-service calls for flows that are naturally one boundary (configuring a
    monitor and reading its reports). One service, one Postgres+Redis store.

    NOTE ON THE CONTROL LOOP: the most important behavior — consuming
    `fp.inference.completed`, windowing, scoring, and firing the retrain — is NOT
    an RPC. It is an event-driven loop running inside the service (NATS consumer +
    scorer + policy). This gRPC surface is the CONTROL & OBSERVABILITY plane over
    that loop: configure it, read what it found, watch it live, feed it truth.

    RPC CATEGORIES:
    CONFIG:        ConfigureMonitor, DeleteMonitor, ResetBaseline
    OBSERVABILITY: GetModelHealth, GetMonitorStatus, ListMonitors,
    GetDriftReport, ListDriftReports, StreamDriftEvents
    FEEDBACK:      SubmitGroundTruth (delayed labels → performance decay)

    AUTH: every RPC is guarded by the shared auth interceptor (see auth.proto).
    Drift scores and config are operationally sensitive; reads require monitoring
    read scope, writes (ConfigureMonitor, DeleteMonitor, ResetBaseline,
    SubmitGroundTruth) require write scope. EVERY RPC is additionally TEAM-SCOPED
    by the interceptor from the caller's auth claims — no request carries a team or
    tenancy field (those would be cross-tenant footguns; see per-request notes).
    ============================================================================
    """

    @staticmethod
    def ConfigureMonitor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.monitor.v1.MonitorService/ConfigureMonitor',
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ConfigureMonitorRequest.SerializeToString,
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ConfigureMonitorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMonitor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.monitor.v1.MonitorService/DeleteMonitor',
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.DeleteMonitorRequest.SerializeToString,
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.DeleteMonitorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetBaseline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.monitor.v1.MonitorService/ResetBaseline',
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ResetBaselineRequest.SerializeToString,
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ResetBaselineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.monitor.v1.MonitorService/GetModelHealth',
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetModelHealthRequest.SerializeToString,
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetModelHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMonitorStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.monitor.v1.MonitorService/GetMonitorStatus',
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetMonitorStatusRequest.SerializeToString,
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetMonitorStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMonitors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.monitor.v1.MonitorService/ListMonitors',
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ListMonitorsRequest.SerializeToString,
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ListMonitorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDriftReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.monitor.v1.MonitorService/GetDriftReport',
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetDriftReportRequest.SerializeToString,
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.GetDriftReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDriftReports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.monitor.v1.MonitorService/ListDriftReports',
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ListDriftReportsRequest.SerializeToString,
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.ListDriftReportsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitGroundTruth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.monitor.v1.MonitorService/SubmitGroundTruth',
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.SubmitGroundTruthRequest.SerializeToString,
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.SubmitGroundTruthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDriftEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/forgepoint.monitor.v1.MonitorService/StreamDriftEvents',
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.StreamDriftEventsRequest.SerializeToString,
            forgepoint_dot_monitor_dot_v1_dot_monitor__pb2.StreamDriftEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
