# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from forgepoint.billing.v1 import billing_pb2 as forgepoint_dot_billing_dot_v1_dot_billing__pb2


class BillingServiceStub:
    """============================================================================
    EVENT CONTRACT — billing PRODUCES three events, defined in forgepoint.events.v1
    ============================================================================

    NO event-payload messages are declared here. Billing's three events live in
    the canonical forgepoint.events.v1 package (the platform's single source of
    truth); the outbox poller marshals one of those messages into
    common.v1.EventEnvelope.data (an Any) and publishes it. This file used to
    declare its own UsageRecorded/QuotaExceeded/InvoiceGenerated — DELETED, because
    per-service ad-hoc event messages drifted from their consumers (see import
    block). The canonical contract is referenced (not redefined) here:

    SUBJECT                        PAYLOAD (forgepoint.events.v1)   CONSUMERS
    ─────────────────────────────  ──────────────────────────────  ────────────────────────────
    fp.billing.usage.recorded      events.UsageRecorded            experiment-tracker, dashboards
    fp.billing.quota.exceeded      events.QuotaExceeded            notification, inference-gateway
    fp.billing.invoice.generated   events.InvoiceGenerated         notification

    SUBJECT NOTE (conflict #6): the design doc's fp.billing.> hierarchy listed
    quota.exceeded and invoice.generated explicitly; usage.recorded was implied
    by the outbox example. fp.billing.usage.recorded is the NEW sanctioned
    subject under the existing fp.billing.> tree (added to the design-doc NATS
    hierarchy as part of this alignment).

    MONEY IS FLATTENED IN THE EVENTS (decoupling, not an oversight): the canonical
    events.UsageRecorded carries cost_micros + currency_code (NOT a billing.Money
    and NOT the whole UsageRecord); events.InvoiceGenerated carries total_micros +
    currency_code (NOT a billing.Invoice). WHY: a consumer (Experiment Tracker,
    Notification) must NOT have to compile-depend on this billing API proto just to
    read an event. The handler maps billing.Money/UsageRecord/Invoice -> the flat
    event scalars at publish time, and billing.MeterType -> events.MeterType.

    ALL THREE GO THROUGH THE OUTBOX: each event row is written in the SAME Postgres
    transaction as the business write it describes (the usage/quota update or the
    invoice finalize), then the poller publishes at-least-once. Consumers are
    idempotent on EventEnvelope.id, so at-least-once is safe.

    ============================================================================
    BILLING SERVICE
    ============================================================================

    WHY a single BillingService (not separate Usage / Invoice services):
    Usage and invoicing are the same bounded context — invoices ARE aggregated
    usage. Splitting them would force a cross-service call on every period close
    and fracture the ledger's single source of truth. One service owns the
    `fp_billing` database (usage_events, quotas, rate_plans, invoices, outbox)
    per the database-per-service standard.

    RPC CATEGORIES:
    METERING (write): RecordUsage — the outbox-protected write path. In steady
    state this is driven by the events.InferenceCompleted NATS consumer (and
    events.ModelVersionReady for storage); exposed on gRPC for backfills and
    direct metering.
    PRICING (admin/read): CreateRatePlan (admin write — sets real prices),
    GetRatePlan (read the pricing a team is billed under).
    QUOTA (read): CheckQuota — the gateway's pre-flight; cheap "how much is left"
    answer the gateway caches in Redis (the QuotaExceeded event invalidates it).
    REPORTING (read): GetUsage (aggregated, paged), GetInvoice, ListInvoices
    (paged) — read-only views over the ledger.

    WHY ALL UNARY (no streaming):
    - RecordUsage / CreateRatePlan / CheckQuota are single fact-in / record-out —
    request/reply.
    - GetUsage/ListInvoices return BOUNDED, PAGINATED pages; pagination (not a
    server stream) is the right tool because it gives clients resumability,
    cacheable page tokens, and a natural total_count — the same choice the
    registry's list RPCs made. A server stream would suit an UNBOUNDED live
    feed (e.g. tail usage in real time); that real-time need is served by the
    async events.UsageRecorded NATS event instead, keeping the gRPC surface
    simple.

    QUOTA ENFORCEMENT — two complementary mechanisms:
    CheckQuota is the PULL/pre-flight (gateway asks before forwarding; cache-fill
    cold path). The events.QuotaExceeded outbox event is the PUSH/invalidation
    (the moment a team crosses the cap, the event flips the gateway's Redis cache
    to "blocked"). Eventual consistency between DB and the gateway cache is
    acceptable for a pre-flight — the worst case is a handful of over-quota calls
    slip through before the cache flips, which the next RecordUsage still meters.

    ASCII DIAGRAM — the outbox metering pipeline:

    Inference Gateway ──fp.inference.completed──► Billing NATS consumer
    │ (dedupe on request_id)
    ▼
    ┌─ BEGIN tx ───────────────────────────┐
    │  INSERT usage_record (priced)        │
    │  UPDATE quota counter                │
    │  INSERT outbox(events.UsageRecorded) │
    │  if over quota:                      │
    │     INSERT outbox(events.QuotaExceeded)│
    └─ COMMIT ─────────────────────────────┘
    │
    outbox poller (separate goroutine, at-least-once)
    ▼
    NATS  fp.billing.usage.recorded / .quota.exceeded
    ▼
    Notification / Inference Gateway / Experiment Tracker
    ============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordUsage = channel.unary_unary(
                '/forgepoint.billing.v1.BillingService/RecordUsage',
                request_serializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.RecordUsageRequest.SerializeToString,
                response_deserializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.RecordUsageResponse.FromString,
                _registered_method=True)
        self.CreateRatePlan = channel.unary_unary(
                '/forgepoint.billing.v1.BillingService/CreateRatePlan',
                request_serializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.CreateRatePlanRequest.SerializeToString,
                response_deserializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.CreateRatePlanResponse.FromString,
                _registered_method=True)
        self.GetRatePlan = channel.unary_unary(
                '/forgepoint.billing.v1.BillingService/GetRatePlan',
                request_serializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetRatePlanRequest.SerializeToString,
                response_deserializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetRatePlanResponse.FromString,
                _registered_method=True)
        self.CheckQuota = channel.unary_unary(
                '/forgepoint.billing.v1.BillingService/CheckQuota',
                request_serializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.CheckQuotaRequest.SerializeToString,
                response_deserializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.CheckQuotaResponse.FromString,
                _registered_method=True)
        self.GetUsage = channel.unary_unary(
                '/forgepoint.billing.v1.BillingService/GetUsage',
                request_serializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetUsageRequest.SerializeToString,
                response_deserializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetUsageResponse.FromString,
                _registered_method=True)
        self.GetInvoice = channel.unary_unary(
                '/forgepoint.billing.v1.BillingService/GetInvoice',
                request_serializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetInvoiceRequest.SerializeToString,
                response_deserializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetInvoiceResponse.FromString,
                _registered_method=True)
        self.ListInvoices = channel.unary_unary(
                '/forgepoint.billing.v1.BillingService/ListInvoices',
                request_serializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.ListInvoicesRequest.SerializeToString,
                response_deserializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.ListInvoicesResponse.FromString,
                _registered_method=True)


class BillingServiceServicer:
    """============================================================================
    EVENT CONTRACT — billing PRODUCES three events, defined in forgepoint.events.v1
    ============================================================================

    NO event-payload messages are declared here. Billing's three events live in
    the canonical forgepoint.events.v1 package (the platform's single source of
    truth); the outbox poller marshals one of those messages into
    common.v1.EventEnvelope.data (an Any) and publishes it. This file used to
    declare its own UsageRecorded/QuotaExceeded/InvoiceGenerated — DELETED, because
    per-service ad-hoc event messages drifted from their consumers (see import
    block). The canonical contract is referenced (not redefined) here:

    SUBJECT                        PAYLOAD (forgepoint.events.v1)   CONSUMERS
    ─────────────────────────────  ──────────────────────────────  ────────────────────────────
    fp.billing.usage.recorded      events.UsageRecorded            experiment-tracker, dashboards
    fp.billing.quota.exceeded      events.QuotaExceeded            notification, inference-gateway
    fp.billing.invoice.generated   events.InvoiceGenerated         notification

    SUBJECT NOTE (conflict #6): the design doc's fp.billing.> hierarchy listed
    quota.exceeded and invoice.generated explicitly; usage.recorded was implied
    by the outbox example. fp.billing.usage.recorded is the NEW sanctioned
    subject under the existing fp.billing.> tree (added to the design-doc NATS
    hierarchy as part of this alignment).

    MONEY IS FLATTENED IN THE EVENTS (decoupling, not an oversight): the canonical
    events.UsageRecorded carries cost_micros + currency_code (NOT a billing.Money
    and NOT the whole UsageRecord); events.InvoiceGenerated carries total_micros +
    currency_code (NOT a billing.Invoice). WHY: a consumer (Experiment Tracker,
    Notification) must NOT have to compile-depend on this billing API proto just to
    read an event. The handler maps billing.Money/UsageRecord/Invoice -> the flat
    event scalars at publish time, and billing.MeterType -> events.MeterType.

    ALL THREE GO THROUGH THE OUTBOX: each event row is written in the SAME Postgres
    transaction as the business write it describes (the usage/quota update or the
    invoice finalize), then the poller publishes at-least-once. Consumers are
    idempotent on EventEnvelope.id, so at-least-once is safe.

    ============================================================================
    BILLING SERVICE
    ============================================================================

    WHY a single BillingService (not separate Usage / Invoice services):
    Usage and invoicing are the same bounded context — invoices ARE aggregated
    usage. Splitting them would force a cross-service call on every period close
    and fracture the ledger's single source of truth. One service owns the
    `fp_billing` database (usage_events, quotas, rate_plans, invoices, outbox)
    per the database-per-service standard.

    RPC CATEGORIES:
    METERING (write): RecordUsage — the outbox-protected write path. In steady
    state this is driven by the events.InferenceCompleted NATS consumer (and
    events.ModelVersionReady for storage); exposed on gRPC for backfills and
    direct metering.
    PRICING (admin/read): CreateRatePlan (admin write — sets real prices),
    GetRatePlan (read the pricing a team is billed under).
    QUOTA (read): CheckQuota — the gateway's pre-flight; cheap "how much is left"
    answer the gateway caches in Redis (the QuotaExceeded event invalidates it).
    REPORTING (read): GetUsage (aggregated, paged), GetInvoice, ListInvoices
    (paged) — read-only views over the ledger.

    WHY ALL UNARY (no streaming):
    - RecordUsage / CreateRatePlan / CheckQuota are single fact-in / record-out —
    request/reply.
    - GetUsage/ListInvoices return BOUNDED, PAGINATED pages; pagination (not a
    server stream) is the right tool because it gives clients resumability,
    cacheable page tokens, and a natural total_count — the same choice the
    registry's list RPCs made. A server stream would suit an UNBOUNDED live
    feed (e.g. tail usage in real time); that real-time need is served by the
    async events.UsageRecorded NATS event instead, keeping the gRPC surface
    simple.

    QUOTA ENFORCEMENT — two complementary mechanisms:
    CheckQuota is the PULL/pre-flight (gateway asks before forwarding; cache-fill
    cold path). The events.QuotaExceeded outbox event is the PUSH/invalidation
    (the moment a team crosses the cap, the event flips the gateway's Redis cache
    to "blocked"). Eventual consistency between DB and the gateway cache is
    acceptable for a pre-flight — the worst case is a handful of over-quota calls
    slip through before the cache flips, which the next RecordUsage still meters.

    ASCII DIAGRAM — the outbox metering pipeline:

    Inference Gateway ──fp.inference.completed──► Billing NATS consumer
    │ (dedupe on request_id)
    ▼
    ┌─ BEGIN tx ───────────────────────────┐
    │  INSERT usage_record (priced)        │
    │  UPDATE quota counter                │
    │  INSERT outbox(events.UsageRecorded) │
    │  if over quota:                      │
    │     INSERT outbox(events.QuotaExceeded)│
    └─ COMMIT ─────────────────────────────┘
    │
    outbox poller (separate goroutine, at-least-once)
    ▼
    NATS  fp.billing.usage.recorded / .quota.exceeded
    ▼
    Notification / Inference Gateway / Experiment Tracker
    ============================================================================
    """

    def RecordUsage(self, request, context):
        """RecordUsage meters one billable action and writes it to the ledger via the
        outbox. The cost is COMPUTED server-side from the team's rate plan — the
        request carries only meter facts, never a price (see RecordUsageRequest).
        Idempotent via idempotency_key, so a redelivered events.InferenceCompleted or
        a client retry never double-bills. This is the outbox pattern's write half.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRatePlan(self, request, context):
        """CreateRatePlan defines a new priced plan (unit prices, free allowances, quota
        caps). ADMIN-ONLY — it sets real money. id/created_at are server-assigned
        (mass-assignment guard); idempotent via idempotency_key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRatePlan(self, request, context):
        """GetRatePlan returns a single rate plan's pricing so a BFF/CLI can show a team
        what it will be billed. Non-admins may read only their own team's plan.
        Read-only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckQuota(self, request, context):
        """CheckQuota is the gateway's pre-flight: returns remaining quota + an
        `exceeded` flag for a team/meter so the gateway can reject/throttle before
        forwarding. Server-computed; non-admins scoped to their own team. Read-only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsage(self, request, context):
        """GetUsage returns aggregated, paginated usage summaries (per-meter rollups +
        grand total) for a team over a time window. Non-admins are scoped to their
        own team server-side. Read-only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInvoice(self, request, context):
        """GetInvoice fetches a single invoice by id, with its server-computed line
        items and total. Cross-team reads are denied (tenant isolation). Read-only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInvoices(self, request, context):
        """ListInvoices returns a team's invoices newest-first, paginated, optionally
        filtered by status (e.g. OVERDUE for dunning). Read-only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordUsage,
                    request_deserializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.RecordUsageRequest.FromString,
                    response_serializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.RecordUsageResponse.SerializeToString,
            ),
            'CreateRatePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRatePlan,
                    request_deserializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.CreateRatePlanRequest.FromString,
                    response_serializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.CreateRatePlanResponse.SerializeToString,
            ),
            'GetRatePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRatePlan,
                    request_deserializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetRatePlanRequest.FromString,
                    response_serializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetRatePlanResponse.SerializeToString,
            ),
            'CheckQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckQuota,
                    request_deserializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.CheckQuotaRequest.FromString,
                    response_serializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.CheckQuotaResponse.SerializeToString,
            ),
            'GetUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsage,
                    request_deserializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetUsageRequest.FromString,
                    response_serializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetUsageResponse.SerializeToString,
            ),
            'GetInvoice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInvoice,
                    request_deserializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetInvoiceRequest.FromString,
                    response_serializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetInvoiceResponse.SerializeToString,
            ),
            'ListInvoices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInvoices,
                    request_deserializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.ListInvoicesRequest.FromString,
                    response_serializer=forgepoint_dot_billing_dot_v1_dot_billing__pb2.ListInvoicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forgepoint.billing.v1.BillingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forgepoint.billing.v1.BillingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BillingService:
    """============================================================================
    EVENT CONTRACT — billing PRODUCES three events, defined in forgepoint.events.v1
    ============================================================================

    NO event-payload messages are declared here. Billing's three events live in
    the canonical forgepoint.events.v1 package (the platform's single source of
    truth); the outbox poller marshals one of those messages into
    common.v1.EventEnvelope.data (an Any) and publishes it. This file used to
    declare its own UsageRecorded/QuotaExceeded/InvoiceGenerated — DELETED, because
    per-service ad-hoc event messages drifted from their consumers (see import
    block). The canonical contract is referenced (not redefined) here:

    SUBJECT                        PAYLOAD (forgepoint.events.v1)   CONSUMERS
    ─────────────────────────────  ──────────────────────────────  ────────────────────────────
    fp.billing.usage.recorded      events.UsageRecorded            experiment-tracker, dashboards
    fp.billing.quota.exceeded      events.QuotaExceeded            notification, inference-gateway
    fp.billing.invoice.generated   events.InvoiceGenerated         notification

    SUBJECT NOTE (conflict #6): the design doc's fp.billing.> hierarchy listed
    quota.exceeded and invoice.generated explicitly; usage.recorded was implied
    by the outbox example. fp.billing.usage.recorded is the NEW sanctioned
    subject under the existing fp.billing.> tree (added to the design-doc NATS
    hierarchy as part of this alignment).

    MONEY IS FLATTENED IN THE EVENTS (decoupling, not an oversight): the canonical
    events.UsageRecorded carries cost_micros + currency_code (NOT a billing.Money
    and NOT the whole UsageRecord); events.InvoiceGenerated carries total_micros +
    currency_code (NOT a billing.Invoice). WHY: a consumer (Experiment Tracker,
    Notification) must NOT have to compile-depend on this billing API proto just to
    read an event. The handler maps billing.Money/UsageRecord/Invoice -> the flat
    event scalars at publish time, and billing.MeterType -> events.MeterType.

    ALL THREE GO THROUGH THE OUTBOX: each event row is written in the SAME Postgres
    transaction as the business write it describes (the usage/quota update or the
    invoice finalize), then the poller publishes at-least-once. Consumers are
    idempotent on EventEnvelope.id, so at-least-once is safe.

    ============================================================================
    BILLING SERVICE
    ============================================================================

    WHY a single BillingService (not separate Usage / Invoice services):
    Usage and invoicing are the same bounded context — invoices ARE aggregated
    usage. Splitting them would force a cross-service call on every period close
    and fracture the ledger's single source of truth. One service owns the
    `fp_billing` database (usage_events, quotas, rate_plans, invoices, outbox)
    per the database-per-service standard.

    RPC CATEGORIES:
    METERING (write): RecordUsage — the outbox-protected write path. In steady
    state this is driven by the events.InferenceCompleted NATS consumer (and
    events.ModelVersionReady for storage); exposed on gRPC for backfills and
    direct metering.
    PRICING (admin/read): CreateRatePlan (admin write — sets real prices),
    GetRatePlan (read the pricing a team is billed under).
    QUOTA (read): CheckQuota — the gateway's pre-flight; cheap "how much is left"
    answer the gateway caches in Redis (the QuotaExceeded event invalidates it).
    REPORTING (read): GetUsage (aggregated, paged), GetInvoice, ListInvoices
    (paged) — read-only views over the ledger.

    WHY ALL UNARY (no streaming):
    - RecordUsage / CreateRatePlan / CheckQuota are single fact-in / record-out —
    request/reply.
    - GetUsage/ListInvoices return BOUNDED, PAGINATED pages; pagination (not a
    server stream) is the right tool because it gives clients resumability,
    cacheable page tokens, and a natural total_count — the same choice the
    registry's list RPCs made. A server stream would suit an UNBOUNDED live
    feed (e.g. tail usage in real time); that real-time need is served by the
    async events.UsageRecorded NATS event instead, keeping the gRPC surface
    simple.

    QUOTA ENFORCEMENT — two complementary mechanisms:
    CheckQuota is the PULL/pre-flight (gateway asks before forwarding; cache-fill
    cold path). The events.QuotaExceeded outbox event is the PUSH/invalidation
    (the moment a team crosses the cap, the event flips the gateway's Redis cache
    to "blocked"). Eventual consistency between DB and the gateway cache is
    acceptable for a pre-flight — the worst case is a handful of over-quota calls
    slip through before the cache flips, which the next RecordUsage still meters.

    ASCII DIAGRAM — the outbox metering pipeline:

    Inference Gateway ──fp.inference.completed──► Billing NATS consumer
    │ (dedupe on request_id)
    ▼
    ┌─ BEGIN tx ───────────────────────────┐
    │  INSERT usage_record (priced)        │
    │  UPDATE quota counter                │
    │  INSERT outbox(events.UsageRecorded) │
    │  if over quota:                      │
    │     INSERT outbox(events.QuotaExceeded)│
    └─ COMMIT ─────────────────────────────┘
    │
    outbox poller (separate goroutine, at-least-once)
    ▼
    NATS  fp.billing.usage.recorded / .quota.exceeded
    ▼
    Notification / Inference Gateway / Experiment Tracker
    ============================================================================
    """

    @staticmethod
    def RecordUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.billing.v1.BillingService/RecordUsage',
            forgepoint_dot_billing_dot_v1_dot_billing__pb2.RecordUsageRequest.SerializeToString,
            forgepoint_dot_billing_dot_v1_dot_billing__pb2.RecordUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRatePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.billing.v1.BillingService/CreateRatePlan',
            forgepoint_dot_billing_dot_v1_dot_billing__pb2.CreateRatePlanRequest.SerializeToString,
            forgepoint_dot_billing_dot_v1_dot_billing__pb2.CreateRatePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRatePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.billing.v1.BillingService/GetRatePlan',
            forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetRatePlanRequest.SerializeToString,
            forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetRatePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.billing.v1.BillingService/CheckQuota',
            forgepoint_dot_billing_dot_v1_dot_billing__pb2.CheckQuotaRequest.SerializeToString,
            forgepoint_dot_billing_dot_v1_dot_billing__pb2.CheckQuotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.billing.v1.BillingService/GetUsage',
            forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetUsageRequest.SerializeToString,
            forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInvoice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.billing.v1.BillingService/GetInvoice',
            forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetInvoiceRequest.SerializeToString,
            forgepoint_dot_billing_dot_v1_dot_billing__pb2.GetInvoiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInvoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.billing.v1.BillingService/ListInvoices',
            forgepoint_dot_billing_dot_v1_dot_billing__pb2.ListInvoicesRequest.SerializeToString,
            forgepoint_dot_billing_dot_v1_dot_billing__pb2.ListInvoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
