# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from forgepoint.pipeline.v1 import pipeline_pb2 as forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2


class PipelineOrchestratorServiceStub:
    """============================================================================
    EVENT PAYLOADS — DEFINED IN forgepoint/events/v1/events.proto, NOT HERE
    ============================================================================

    This proto used to declare its own PipelineStartedEvent / StepCompletedEvent /
    StepFailedEvent / CompensationTriggeredEvent / PipelineCompletedEvent /
    PipelineFailedEvent messages. They have been DELETED. The platform's single
    source of truth for every NATS payload is forgepoint/events/v1/events.proto;
    re-declaring payloads per service was exactly the incoherence that file exists
    to fix (two services disagreeing on the same event, etc. — see its DESIGN
    block). This service now publishes/consumes the canonical types instead.

    PRODUCES (this service's handler marshals these into common.EventEnvelope.data):
    events.PipelineStarted        → fp.pipelines.started
    events.StepCompleted          → fp.pipelines.step.completed
    events.StepFailed             → fp.pipelines.step.failed
    events.CompensationTriggered  → fp.pipelines.compensation.triggered
    events.PipelineCompleted      → fp.pipelines.completed
    events.PipelineFailed         → fp.pipelines.failed
    events.ModelDeployed          → fp.pipelines.model.deployed    (DEPLOY/PROMOTE saga step)
    events.ModelUndeployed        → fp.pipelines.model.undeployed  (teardown / rollback compensation)

    CONSUMES:
    events.ModelDriftDetected     ← fp.models.drift.detected
    On severity == DRIFT_SEVERITY_CRITICAL AND auto_retrain == true, the
    consumer calls THIS service's TriggerExecution(retrain_pipeline_id,
    input = retrain_context) — closing serve → monitor → retrain. The
    inbound EventEnvelope.id (and the report_id business handle) dedupe
    redeliveries so a drift report never double-triggers a retrain.

    THIN-EVENT / FAT-READ: the lifecycle events carry IDs + a snapshot of essential
    fields, NOT the whole Execution. A consumer that wants the full per-step
    timeline calls GetExecution. The model-deploy events are the exception — they
    are FAT-BUT-FLAT (endpoint + weight_bps) so the gateway/serving can act with no
    callback. (See events.proto for the per-event field rationale.)
    ============================================================================

    ============================================================================
    PIPELINE ORCHESTRATOR SERVICE
    ============================================================================

    WHY ONE SERVICE WITH THESE RPCs: the service has two responsibilities —
    DEFINING workflows (CreatePipeline / ListPipelines) and RUNNING + OBSERVING
    them (Trigger / Get / Watch / Cancel / List executions). They share the same
    durable store and domain model, so they live behind one service boundary.

    STREAMING CHOICE (interview-critical): only WatchExecution is server-
    streaming; everything else is unary. WHY:
    - WatchExecution: the orchestrator is the SINGLE source of truth for saga
    state and PUSHES transitions as they happen. One client request →
    many server messages = SERVER-STREAMING. Polling GetExecution in a loop
    would be wasteful (most polls see no change) and laggy. Long-lived push
    is the natural fit, and the BFF bridges it to SSE for the browser.
    - Everything else is a single request/response → unary. We do NOT use
    client-streaming or bidi anywhere here: the client never sends a stream of
    data to the orchestrator; it issues discrete commands.

    LEADER ELECTION (deployment note, surfaced for interviews): although the gRPC
    API can be served by many replicas, only the ELECTED LEADER actually drives
    sagas (runs steps, writes checkpoints). This prevents two pods from executing
    the same saga concurrently and double-applying side effects. Read RPCs
    (Get/List/Watch) can be served by any replica from the shared DB.

    CALL FLOW (closing the loop):
    Model Monitor detects drift
    │ gRPC
    ▼
    PipelineOrchestratorService.TriggerExecution(training pipeline, drift report)
    │  saga/DAG: retrain → evaluate → register → deploy → canary → promote
    ▼
    emits fp.pipelines.* events → Notification + Experiment Tracker
    ============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePipeline = channel.unary_unary(
                '/forgepoint.pipeline.v1.PipelineOrchestratorService/CreatePipeline',
                request_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.CreatePipelineRequest.SerializeToString,
                response_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.CreatePipelineResponse.FromString,
                _registered_method=True)
        self.ListPipelines = channel.unary_unary(
                '/forgepoint.pipeline.v1.PipelineOrchestratorService/ListPipelines',
                request_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.ListPipelinesRequest.SerializeToString,
                response_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.ListPipelinesResponse.FromString,
                _registered_method=True)
        self.GetPipeline = channel.unary_unary(
                '/forgepoint.pipeline.v1.PipelineOrchestratorService/GetPipeline',
                request_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.GetPipelineRequest.SerializeToString,
                response_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.GetPipelineResponse.FromString,
                _registered_method=True)
        self.UpdatePipeline = channel.unary_unary(
                '/forgepoint.pipeline.v1.PipelineOrchestratorService/UpdatePipeline',
                request_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.UpdatePipelineRequest.SerializeToString,
                response_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.UpdatePipelineResponse.FromString,
                _registered_method=True)
        self.DeletePipeline = channel.unary_unary(
                '/forgepoint.pipeline.v1.PipelineOrchestratorService/DeletePipeline',
                request_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.DeletePipelineRequest.SerializeToString,
                response_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.DeletePipelineResponse.FromString,
                _registered_method=True)
        self.TriggerExecution = channel.unary_unary(
                '/forgepoint.pipeline.v1.PipelineOrchestratorService/TriggerExecution',
                request_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.TriggerExecutionRequest.SerializeToString,
                response_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.TriggerExecutionResponse.FromString,
                _registered_method=True)
        self.GetExecution = channel.unary_unary(
                '/forgepoint.pipeline.v1.PipelineOrchestratorService/GetExecution',
                request_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.GetExecutionRequest.SerializeToString,
                response_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.GetExecutionResponse.FromString,
                _registered_method=True)
        self.WatchExecution = channel.unary_stream(
                '/forgepoint.pipeline.v1.PipelineOrchestratorService/WatchExecution',
                request_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.WatchExecutionRequest.SerializeToString,
                response_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.WatchExecutionResponse.FromString,
                _registered_method=True)
        self.CancelExecution = channel.unary_unary(
                '/forgepoint.pipeline.v1.PipelineOrchestratorService/CancelExecution',
                request_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.CancelExecutionRequest.SerializeToString,
                response_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.CancelExecutionResponse.FromString,
                _registered_method=True)
        self.ListExecutions = channel.unary_unary(
                '/forgepoint.pipeline.v1.PipelineOrchestratorService/ListExecutions',
                request_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.ListExecutionsRequest.SerializeToString,
                response_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.ListExecutionsResponse.FromString,
                _registered_method=True)


class PipelineOrchestratorServiceServicer:
    """============================================================================
    EVENT PAYLOADS — DEFINED IN forgepoint/events/v1/events.proto, NOT HERE
    ============================================================================

    This proto used to declare its own PipelineStartedEvent / StepCompletedEvent /
    StepFailedEvent / CompensationTriggeredEvent / PipelineCompletedEvent /
    PipelineFailedEvent messages. They have been DELETED. The platform's single
    source of truth for every NATS payload is forgepoint/events/v1/events.proto;
    re-declaring payloads per service was exactly the incoherence that file exists
    to fix (two services disagreeing on the same event, etc. — see its DESIGN
    block). This service now publishes/consumes the canonical types instead.

    PRODUCES (this service's handler marshals these into common.EventEnvelope.data):
    events.PipelineStarted        → fp.pipelines.started
    events.StepCompleted          → fp.pipelines.step.completed
    events.StepFailed             → fp.pipelines.step.failed
    events.CompensationTriggered  → fp.pipelines.compensation.triggered
    events.PipelineCompleted      → fp.pipelines.completed
    events.PipelineFailed         → fp.pipelines.failed
    events.ModelDeployed          → fp.pipelines.model.deployed    (DEPLOY/PROMOTE saga step)
    events.ModelUndeployed        → fp.pipelines.model.undeployed  (teardown / rollback compensation)

    CONSUMES:
    events.ModelDriftDetected     ← fp.models.drift.detected
    On severity == DRIFT_SEVERITY_CRITICAL AND auto_retrain == true, the
    consumer calls THIS service's TriggerExecution(retrain_pipeline_id,
    input = retrain_context) — closing serve → monitor → retrain. The
    inbound EventEnvelope.id (and the report_id business handle) dedupe
    redeliveries so a drift report never double-triggers a retrain.

    THIN-EVENT / FAT-READ: the lifecycle events carry IDs + a snapshot of essential
    fields, NOT the whole Execution. A consumer that wants the full per-step
    timeline calls GetExecution. The model-deploy events are the exception — they
    are FAT-BUT-FLAT (endpoint + weight_bps) so the gateway/serving can act with no
    callback. (See events.proto for the per-event field rationale.)
    ============================================================================

    ============================================================================
    PIPELINE ORCHESTRATOR SERVICE
    ============================================================================

    WHY ONE SERVICE WITH THESE RPCs: the service has two responsibilities —
    DEFINING workflows (CreatePipeline / ListPipelines) and RUNNING + OBSERVING
    them (Trigger / Get / Watch / Cancel / List executions). They share the same
    durable store and domain model, so they live behind one service boundary.

    STREAMING CHOICE (interview-critical): only WatchExecution is server-
    streaming; everything else is unary. WHY:
    - WatchExecution: the orchestrator is the SINGLE source of truth for saga
    state and PUSHES transitions as they happen. One client request →
    many server messages = SERVER-STREAMING. Polling GetExecution in a loop
    would be wasteful (most polls see no change) and laggy. Long-lived push
    is the natural fit, and the BFF bridges it to SSE for the browser.
    - Everything else is a single request/response → unary. We do NOT use
    client-streaming or bidi anywhere here: the client never sends a stream of
    data to the orchestrator; it issues discrete commands.

    LEADER ELECTION (deployment note, surfaced for interviews): although the gRPC
    API can be served by many replicas, only the ELECTED LEADER actually drives
    sagas (runs steps, writes checkpoints). This prevents two pods from executing
    the same saga concurrently and double-applying side effects. Read RPCs
    (Get/List/Watch) can be served by any replica from the shared DB.

    CALL FLOW (closing the loop):
    Model Monitor detects drift
    │ gRPC
    ▼
    PipelineOrchestratorService.TriggerExecution(training pipeline, drift report)
    │  saga/DAG: retrain → evaluate → register → deploy → canary → promote
    ▼
    emits fp.pipelines.* events → Notification + Experiment Tracker
    ============================================================================
    """

    def CreatePipeline(self, request, context):
        """CreatePipeline registers a new pipeline TEMPLATE (saga or DAG). The server
        validates the step graph (known types, valid depends_on, no cycles, valid
        compensation pointers) and assigns id/created_by/created_at server-side.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPipelines(self, request, context):
        """ListPipelines returns a paginated list of pipeline templates within the
        caller's team/RBAC scope, optionally filtered by type.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPipeline(self, request, context):
        """GetPipeline fetches one pipeline TEMPLATE by id (full step graph), scoped to
        the caller's team/RBAC. Point lookup for the CLI/UI before triggering a run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePipeline(self, request, context):
        """UpdatePipeline edits a template's name/steps in place (id and execution
        history preserved). Re-validates the step graph; type is immutable.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePipeline(self, request, context):
        """DeletePipeline soft-deletes (archives) a template so it can no longer be
        listed or triggered, while preserving past executions' lineage. Rejected if
        a non-terminal execution of the pipeline is still in flight.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerExecution(self, request, context):
        """TriggerExecution starts a new run of a pipeline. Supports an idempotency_key
        so retries don't double-trigger (exactly-once from the caller's view). The
        orchestrator owns the resulting Execution's lifecycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExecution(self, request, context):
        """GetExecution fetches the current state of a run (point-in-time), including
        its per-step timeline. Cheap, stateless poll — use Watch for live updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchExecution(self, request, context):
        """WatchExecution opens a SERVER-STREAMING feed of live updates for one run.
        The orchestrator pushes a WatchExecutionResponse on every state transition until
        the run reaches a terminal state (COMPLETED/FAILED/CANCELLED), then closes
        the stream. With include_current_state=true the server first replays the
        current state, avoiding a get-then-watch race.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelExecution(self, request, context):
        """CancelExecution requests a graceful stop. The run transitions to
        COMPENSATING (undo completed steps in reverse) and then CANCELLED.
        Returns the Execution so the caller sees the immediate transition.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListExecutions(self, request, context):
        """ListExecutions returns a paginated, filterable list of runs (by pipeline
        and/or status). page_size is capped server-side. List items omit per-step
        detail; fetch GetExecution for the full timeline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PipelineOrchestratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePipeline,
                    request_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.CreatePipelineRequest.FromString,
                    response_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.CreatePipelineResponse.SerializeToString,
            ),
            'ListPipelines': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPipelines,
                    request_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.ListPipelinesRequest.FromString,
                    response_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.ListPipelinesResponse.SerializeToString,
            ),
            'GetPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPipeline,
                    request_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.GetPipelineRequest.FromString,
                    response_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.GetPipelineResponse.SerializeToString,
            ),
            'UpdatePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePipeline,
                    request_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.UpdatePipelineRequest.FromString,
                    response_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.UpdatePipelineResponse.SerializeToString,
            ),
            'DeletePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePipeline,
                    request_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.DeletePipelineRequest.FromString,
                    response_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.DeletePipelineResponse.SerializeToString,
            ),
            'TriggerExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerExecution,
                    request_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.TriggerExecutionRequest.FromString,
                    response_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.TriggerExecutionResponse.SerializeToString,
            ),
            'GetExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecution,
                    request_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.GetExecutionRequest.FromString,
                    response_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.GetExecutionResponse.SerializeToString,
            ),
            'WatchExecution': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchExecution,
                    request_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.WatchExecutionRequest.FromString,
                    response_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.WatchExecutionResponse.SerializeToString,
            ),
            'CancelExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelExecution,
                    request_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.CancelExecutionRequest.FromString,
                    response_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.CancelExecutionResponse.SerializeToString,
            ),
            'ListExecutions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListExecutions,
                    request_deserializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.ListExecutionsRequest.FromString,
                    response_serializer=forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.ListExecutionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forgepoint.pipeline.v1.PipelineOrchestratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forgepoint.pipeline.v1.PipelineOrchestratorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PipelineOrchestratorService:
    """============================================================================
    EVENT PAYLOADS — DEFINED IN forgepoint/events/v1/events.proto, NOT HERE
    ============================================================================

    This proto used to declare its own PipelineStartedEvent / StepCompletedEvent /
    StepFailedEvent / CompensationTriggeredEvent / PipelineCompletedEvent /
    PipelineFailedEvent messages. They have been DELETED. The platform's single
    source of truth for every NATS payload is forgepoint/events/v1/events.proto;
    re-declaring payloads per service was exactly the incoherence that file exists
    to fix (two services disagreeing on the same event, etc. — see its DESIGN
    block). This service now publishes/consumes the canonical types instead.

    PRODUCES (this service's handler marshals these into common.EventEnvelope.data):
    events.PipelineStarted        → fp.pipelines.started
    events.StepCompleted          → fp.pipelines.step.completed
    events.StepFailed             → fp.pipelines.step.failed
    events.CompensationTriggered  → fp.pipelines.compensation.triggered
    events.PipelineCompleted      → fp.pipelines.completed
    events.PipelineFailed         → fp.pipelines.failed
    events.ModelDeployed          → fp.pipelines.model.deployed    (DEPLOY/PROMOTE saga step)
    events.ModelUndeployed        → fp.pipelines.model.undeployed  (teardown / rollback compensation)

    CONSUMES:
    events.ModelDriftDetected     ← fp.models.drift.detected
    On severity == DRIFT_SEVERITY_CRITICAL AND auto_retrain == true, the
    consumer calls THIS service's TriggerExecution(retrain_pipeline_id,
    input = retrain_context) — closing serve → monitor → retrain. The
    inbound EventEnvelope.id (and the report_id business handle) dedupe
    redeliveries so a drift report never double-triggers a retrain.

    THIN-EVENT / FAT-READ: the lifecycle events carry IDs + a snapshot of essential
    fields, NOT the whole Execution. A consumer that wants the full per-step
    timeline calls GetExecution. The model-deploy events are the exception — they
    are FAT-BUT-FLAT (endpoint + weight_bps) so the gateway/serving can act with no
    callback. (See events.proto for the per-event field rationale.)
    ============================================================================

    ============================================================================
    PIPELINE ORCHESTRATOR SERVICE
    ============================================================================

    WHY ONE SERVICE WITH THESE RPCs: the service has two responsibilities —
    DEFINING workflows (CreatePipeline / ListPipelines) and RUNNING + OBSERVING
    them (Trigger / Get / Watch / Cancel / List executions). They share the same
    durable store and domain model, so they live behind one service boundary.

    STREAMING CHOICE (interview-critical): only WatchExecution is server-
    streaming; everything else is unary. WHY:
    - WatchExecution: the orchestrator is the SINGLE source of truth for saga
    state and PUSHES transitions as they happen. One client request →
    many server messages = SERVER-STREAMING. Polling GetExecution in a loop
    would be wasteful (most polls see no change) and laggy. Long-lived push
    is the natural fit, and the BFF bridges it to SSE for the browser.
    - Everything else is a single request/response → unary. We do NOT use
    client-streaming or bidi anywhere here: the client never sends a stream of
    data to the orchestrator; it issues discrete commands.

    LEADER ELECTION (deployment note, surfaced for interviews): although the gRPC
    API can be served by many replicas, only the ELECTED LEADER actually drives
    sagas (runs steps, writes checkpoints). This prevents two pods from executing
    the same saga concurrently and double-applying side effects. Read RPCs
    (Get/List/Watch) can be served by any replica from the shared DB.

    CALL FLOW (closing the loop):
    Model Monitor detects drift
    │ gRPC
    ▼
    PipelineOrchestratorService.TriggerExecution(training pipeline, drift report)
    │  saga/DAG: retrain → evaluate → register → deploy → canary → promote
    ▼
    emits fp.pipelines.* events → Notification + Experiment Tracker
    ============================================================================
    """

    @staticmethod
    def CreatePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.pipeline.v1.PipelineOrchestratorService/CreatePipeline',
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.CreatePipelineRequest.SerializeToString,
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.CreatePipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPipelines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.pipeline.v1.PipelineOrchestratorService/ListPipelines',
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.ListPipelinesRequest.SerializeToString,
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.ListPipelinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.pipeline.v1.PipelineOrchestratorService/GetPipeline',
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.GetPipelineRequest.SerializeToString,
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.GetPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.pipeline.v1.PipelineOrchestratorService/UpdatePipeline',
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.UpdatePipelineRequest.SerializeToString,
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.UpdatePipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.pipeline.v1.PipelineOrchestratorService/DeletePipeline',
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.DeletePipelineRequest.SerializeToString,
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.DeletePipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.pipeline.v1.PipelineOrchestratorService/TriggerExecution',
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.TriggerExecutionRequest.SerializeToString,
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.TriggerExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.pipeline.v1.PipelineOrchestratorService/GetExecution',
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.GetExecutionRequest.SerializeToString,
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.GetExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/forgepoint.pipeline.v1.PipelineOrchestratorService/WatchExecution',
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.WatchExecutionRequest.SerializeToString,
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.WatchExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.pipeline.v1.PipelineOrchestratorService/CancelExecution',
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.CancelExecutionRequest.SerializeToString,
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.CancelExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListExecutions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.pipeline.v1.PipelineOrchestratorService/ListExecutions',
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.ListExecutionsRequest.SerializeToString,
            forgepoint_dot_pipeline_dot_v1_dot_pipeline__pb2.ListExecutionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
