# ============================================================================
# dev — ENVIRONMENT VARIABLES
# ============================================================================
# Every knob the modules expose is surfaced here with a DEV-appropriate default
# (small + cheap). staging/prod copy this directory and override via *.tfvars —
# the modules don't change between environments, only these values do.
#
# Nothing secret lives here: DB/Redis credentials are GENERATED by Terraform and
# stored in Secrets Manager (see the rds/elasticache modules). No account IDs are
# hardcoded — where one is needed (bucket names) it's read from a data source at
# plan time.
# ============================================================================

variable "environment" {
  description = "Environment name — feeds the Environment tag and resource name prefixes. \"dev\" here; \"staging\"/\"prod\" in their copies."
  type        = string
  default     = "dev"
}

variable "aws_region" {
  description = "AWS region to deploy into. No region is hardcoded anywhere else — this single var drives the provider and all region-derived names (VPC endpoints, ECR URLs). Override per deployment."
  type        = string
  default     = "us-east-1"
}

# ---- Networking ------------------------------------------------------------
variable "vpc_cidr" {
  description = "VPC CIDR. /16 leaves ample room for pod IPs (VPC-CNI assigns real IPs)."
  type        = string
  default     = "10.0.0.0/16"
}

variable "az_count" {
  description = "AZs to span. 3 for HA even in dev (cost is mostly in NAT, which single_nat_gateway controls separately)."
  type        = number
  default     = 3
}

variable "single_nat_gateway" {
  description = "Dev: TRUE — one NAT gateway for all private subnets (saves ~$64/mo vs three). Prod: FALSE for per-AZ NAT resilience."
  type        = bool
  default     = true
}

# ---- EKS -------------------------------------------------------------------
variable "cluster_version" {
  description = "EKS Kubernetes version."
  type        = string
  default     = "1.30"
}

variable "eks_public_access" {
  description = "Expose the K8s API publicly (CIDR-restricted). SECURE DEFAULT: false — kubectl/helm must run from within the VPC (bastion or VPN). Set true in a personal throwaway dev cluster AND specify eks_public_access_cidrs to your egress IP. Never enable without restricting CIDRs."
  type        = bool
  default     = false
}

variable "eks_public_access_cidrs" {
  description = "CIDRs allowed to reach the public API endpoint when eks_public_access=true. SECURE DEFAULT: empty list (EKS interprets this as \"allow none\" when the public endpoint is disabled; when you enable the public endpoint set this to your VPN/office IP, e.g. [\"203.0.113.10/32\"]). NEVER set to [\"0.0.0.0/0\"] — that makes the Kubernetes API world-reachable, a critical CIS finding."
  type        = list(string)
  default     = []
}

variable "node_instance_types" {
  description = "Node group instance types. Dev: t3.medium."
  type        = list(string)
  default     = ["t3.medium"]
}

variable "node_desired_size" {
  description = "Desired node count (dev: 2)."
  type        = number
  default     = 2
}

variable "node_min_size" {
  description = "Min node count (dev: 2)."
  type        = number
  default     = 2
}

variable "node_max_size" {
  description = "Max node count (dev: 4)."
  type        = number
  default     = 4
}

variable "node_capacity_type" {
  description = "ON_DEMAND or SPOT. Dev can flip to SPOT to cut node cost ~70% (stateless, replicated services tolerate interruptions)."
  type        = string
  default     = "ON_DEMAND"
}

# ---- RDS (PostgreSQL) ------------------------------------------------------
variable "rds_instance_class" {
  description = "RDS instance class. Dev: db.t3.micro."
  type        = string
  default     = "db.t3.micro"
}

variable "rds_engine_version" {
  description = "PostgreSQL version."
  type        = string
  default     = "16.4"
}

variable "rds_multi_az" {
  description = "RDS multi-AZ standby. Dev: FALSE (cost). Prod: TRUE."
  type        = bool
  default     = false
}

variable "rds_deletion_protection" {
  description = "Block deletion of the DB. Dev: FALSE (teardown). Prod: TRUE."
  type        = bool
  default     = false
}

variable "rds_backup_retention_days" {
  description = "Automated backup retention. Dev: 7."
  type        = number
  default     = 7
}

# ---- ElastiCache (Redis) ---------------------------------------------------
variable "redis_node_type" {
  description = "ElastiCache node type. Dev: cache.t3.micro."
  type        = string
  default     = "cache.t3.micro"
}

variable "redis_engine_version" {
  description = "Redis engine version."
  type        = string
  default     = "7.1"
}

variable "redis_num_nodes" {
  description = "Cache nodes. Dev: 1 (no failover). Prod: >=2 with redis_automatic_failover=true."
  type        = number
  default     = 1
}

variable "redis_automatic_failover" {
  description = "Auto-promote a replica on primary failure. Requires redis_num_nodes>=2, so FALSE in single-node dev."
  type        = bool
  default     = false
}
