# ============================================================================
# dev — VERSION PINS  (mirror of /deploy/terraform/versions.tf)
# ============================================================================
# Each environment is a self-contained rootmodule and must declare its own
# required_providers. We keep these constraints IDENTICAL to the root versions.tf
# so every environment locks the same versions. The committed .terraform.lock.hcl
# (generated by `terraform init`) then freezes exact versions + checksums.
#
# To produce staging/prod: copy this whole dev/ directory and keep this file
# unchanged — only the *.tfvars (sizes/toggles) differ between environments.
# ============================================================================

terraform {
  required_version = ">= 1.9.0, < 2.0.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.60"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    # kubernetes: lets this stack manage in-cluster objects (e.g. IRSA SA
    # annotations) after the cluster exists. Configured in providers.tf.
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.31"
    }
  }
}
