# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from forgepoint.registry.v1 import registry_pb2 as forgepoint_dot_registry_dot_v1_dot_registry__pb2


class RegistryServiceStub:
    """============================================================================
    EVENTS THIS SERVICE PUBLISHES — defined in forgepoint.events.v1, NOT here
    ============================================================================

    WHY THERE ARE NO EVENT MESSAGES IN THIS FILE ANYMORE (this is deliberate):
    This proto previously defined its OWN ModelRegistered / ModelVersionCreated /
    ModelPromoted / ModelArchived payloads. An adversarial cross-service review
    found per-service event messages DRIFTING from the consumers that read them
    (mismatched names, missing fields, two services both claiming one event).
    The fix: ONE canonical event package, forgepoint.events.v1, owned and
    buf-breaking-guarded independently of any service's API. Those four ad-hoc
    messages have been DELETED from this file and now live, canonically, in
    proto/forgepoint/events/v1/events.proto. The registry handler marshals an
    eventsv1.* message into common.v1.EventEnvelope.data (an Any) at publish time.

    This also realizes the "event schema is DECOUPLED from API schema" rule: the
    old registry events EMBEDDED the full registry.Model / registry.ModelVersion,
    which coupled every consumer's build to this proto. The canonical events
    instead carry FLAT ids + the specific fields consumers need, so a consumer
    depends only on eventsv1 + common — never on registry's API types.

    THE FIVE EVENTS REGISTRY PRODUCES (subject · canonical message · key consumers):
    fp.models.registered       · events.ModelRegistered     · pipeline-orchestrator, experiment-tracker
    fp.models.version.created  · events.ModelVersionCreated · experiment-tracker
    fp.models.version.ready    · events.ModelVersionReady   · serving, billing, pipeline-orchestrator   (NEW)
    fp.models.promoted         · events.ModelPromoted       · inference-gateway, serving, model-monitor, billing
    fp.models.archived         · events.ModelArchived       · inference-gateway, serving, billing

    RPC → EVENT(S) it emits on commit:
    RegisterModel        → events.ModelRegistered
    CreateVersion        → events.ModelVersionCreated   (status=PENDING_UPLOAD)
    ConfirmVersionUpload → events.ModelVersionReady     (status PENDING_UPLOAD→READY; NONE on →FAILED)
    PromoteVersion       → events.ModelPromoted         (carries from/to + demoted version — the atomic swap)
    DeleteModel          → events.ModelArchived
    UpdateModel          → (no canonical event — description/tag edits aren't a published fact)

    ENUM MAPPING AT THE BOUNDARY: registry.ModelStage values are mapped to the
    mirror events.ModelStage explicitly in the handler (not cast), per the
    decoupling note on the ModelStage enum above. CONSUMERS that need the
    PENDING_UPLOAD→READY distinction watch ModelVersionReady, NOT ModelVersionCreated.

    REGISTRY CONSUMES NO EVENTS. Its read-side projection consumer reacts to its
    OWN published events to build the Redis read model (the CQRS loop), but the
    service subscribes to no OTHER service's events — there is no inbound coupling.
    ============================================================================

    ============================================================================
    REGISTRY SERVICE
    ============================================================================

    WHY a single RegistryService spanning both command and query RPCs:
    CQRS separates the read/write MODELS and STORES, not necessarily the API
    surface. Exposing both through one gRPC service keeps the client experience
    simple (one stub) while the IMPLEMENTATION routes commands to the Postgres
    write repo and queries to the Redis read repo. If read and write needed
    independent scaling/deploys we could split them into two services later —
    the proto is structured (clear COMMAND vs QUERY grouping below) so that
    split would be mechanical. This is the pragmatic "logical CQRS, physical
    monolith-of-one-service" choice MLflow's registry also makes.

    STREAMING CHOICE — why everything here is UNARY:
    None of these operations is a long-lived stream. Registrations and
    promotions are discrete commands; lookups return a bounded object; lists are
    PAGINATED (cursor) rather than server-streamed because pagination gives the
    client backpressure, resumability (the page_token survives a disconnect),
    and cacheability that a server stream does not. Contrast with the Pipeline
    Orchestrator's WatchExecution, which IS server-streaming because execution
    progress is a genuine open-ended event feed. Picking unary+pagination here
    is the correct, defensible call (interviewers probe this: "why not stream
    ListModels?" → backpressure + resumable cursor + simpler caching).

    RPC GROUPS:
    COMMANDS (Postgres write, then publish a canonical events.v1 NATS event):
    RegisterModel, UpdateModel, CreateVersion, ConfirmVersionUpload,
    PromoteVersion, DeleteModel
    QUERIES (Redis read projection, eventually consistent):
    GetModel, ListModels, SearchByTag, GetVersion, ListVersions
    STORAGE (object store, presigned URLs — bytes bypass this service):
    GetUploadURL (re-issue), GetDownloadURL  (the FIRST upload URL is returned
    inline by CreateVersion; GetUploadURL re-issues an expired one)
    ============================================================================
    --- COMMANDS (write path → Postgres → NATS event) ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterModel = channel.unary_unary(
                '/forgepoint.registry.v1.RegistryService/RegisterModel',
                request_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.RegisterModelRequest.SerializeToString,
                response_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.RegisterModelResponse.FromString,
                _registered_method=True)
        self.UpdateModel = channel.unary_unary(
                '/forgepoint.registry.v1.RegistryService/UpdateModel',
                request_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.UpdateModelRequest.SerializeToString,
                response_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.UpdateModelResponse.FromString,
                _registered_method=True)
        self.CreateVersion = channel.unary_unary(
                '/forgepoint.registry.v1.RegistryService/CreateVersion',
                request_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.CreateVersionRequest.SerializeToString,
                response_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.CreateVersionResponse.FromString,
                _registered_method=True)
        self.ConfirmVersionUpload = channel.unary_unary(
                '/forgepoint.registry.v1.RegistryService/ConfirmVersionUpload',
                request_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.ConfirmVersionUploadRequest.SerializeToString,
                response_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.ConfirmVersionUploadResponse.FromString,
                _registered_method=True)
        self.PromoteVersion = channel.unary_unary(
                '/forgepoint.registry.v1.RegistryService/PromoteVersion',
                request_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.PromoteVersionRequest.SerializeToString,
                response_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.PromoteVersionResponse.FromString,
                _registered_method=True)
        self.DeleteModel = channel.unary_unary(
                '/forgepoint.registry.v1.RegistryService/DeleteModel',
                request_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.DeleteModelResponse.FromString,
                _registered_method=True)
        self.GetModel = channel.unary_unary(
                '/forgepoint.registry.v1.RegistryService/GetModel',
                request_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetModelRequest.SerializeToString,
                response_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetModelResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/forgepoint.registry.v1.RegistryService/ListModels',
                request_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.SearchByTag = channel.unary_unary(
                '/forgepoint.registry.v1.RegistryService/SearchByTag',
                request_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.SearchByTagRequest.SerializeToString,
                response_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.SearchByTagResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/forgepoint.registry.v1.RegistryService/GetVersion',
                request_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetVersionResponse.FromString,
                _registered_method=True)
        self.ListVersions = channel.unary_unary(
                '/forgepoint.registry.v1.RegistryService/ListVersions',
                request_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.ListVersionsRequest.SerializeToString,
                response_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.ListVersionsResponse.FromString,
                _registered_method=True)
        self.GetUploadURL = channel.unary_unary(
                '/forgepoint.registry.v1.RegistryService/GetUploadURL',
                request_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetUploadURLRequest.SerializeToString,
                response_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetUploadURLResponse.FromString,
                _registered_method=True)
        self.GetDownloadURL = channel.unary_unary(
                '/forgepoint.registry.v1.RegistryService/GetDownloadURL',
                request_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetDownloadURLRequest.SerializeToString,
                response_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetDownloadURLResponse.FromString,
                _registered_method=True)


class RegistryServiceServicer:
    """============================================================================
    EVENTS THIS SERVICE PUBLISHES — defined in forgepoint.events.v1, NOT here
    ============================================================================

    WHY THERE ARE NO EVENT MESSAGES IN THIS FILE ANYMORE (this is deliberate):
    This proto previously defined its OWN ModelRegistered / ModelVersionCreated /
    ModelPromoted / ModelArchived payloads. An adversarial cross-service review
    found per-service event messages DRIFTING from the consumers that read them
    (mismatched names, missing fields, two services both claiming one event).
    The fix: ONE canonical event package, forgepoint.events.v1, owned and
    buf-breaking-guarded independently of any service's API. Those four ad-hoc
    messages have been DELETED from this file and now live, canonically, in
    proto/forgepoint/events/v1/events.proto. The registry handler marshals an
    eventsv1.* message into common.v1.EventEnvelope.data (an Any) at publish time.

    This also realizes the "event schema is DECOUPLED from API schema" rule: the
    old registry events EMBEDDED the full registry.Model / registry.ModelVersion,
    which coupled every consumer's build to this proto. The canonical events
    instead carry FLAT ids + the specific fields consumers need, so a consumer
    depends only on eventsv1 + common — never on registry's API types.

    THE FIVE EVENTS REGISTRY PRODUCES (subject · canonical message · key consumers):
    fp.models.registered       · events.ModelRegistered     · pipeline-orchestrator, experiment-tracker
    fp.models.version.created  · events.ModelVersionCreated · experiment-tracker
    fp.models.version.ready    · events.ModelVersionReady   · serving, billing, pipeline-orchestrator   (NEW)
    fp.models.promoted         · events.ModelPromoted       · inference-gateway, serving, model-monitor, billing
    fp.models.archived         · events.ModelArchived       · inference-gateway, serving, billing

    RPC → EVENT(S) it emits on commit:
    RegisterModel        → events.ModelRegistered
    CreateVersion        → events.ModelVersionCreated   (status=PENDING_UPLOAD)
    ConfirmVersionUpload → events.ModelVersionReady     (status PENDING_UPLOAD→READY; NONE on →FAILED)
    PromoteVersion       → events.ModelPromoted         (carries from/to + demoted version — the atomic swap)
    DeleteModel          → events.ModelArchived
    UpdateModel          → (no canonical event — description/tag edits aren't a published fact)

    ENUM MAPPING AT THE BOUNDARY: registry.ModelStage values are mapped to the
    mirror events.ModelStage explicitly in the handler (not cast), per the
    decoupling note on the ModelStage enum above. CONSUMERS that need the
    PENDING_UPLOAD→READY distinction watch ModelVersionReady, NOT ModelVersionCreated.

    REGISTRY CONSUMES NO EVENTS. Its read-side projection consumer reacts to its
    OWN published events to build the Redis read model (the CQRS loop), but the
    service subscribes to no OTHER service's events — there is no inbound coupling.
    ============================================================================

    ============================================================================
    REGISTRY SERVICE
    ============================================================================

    WHY a single RegistryService spanning both command and query RPCs:
    CQRS separates the read/write MODELS and STORES, not necessarily the API
    surface. Exposing both through one gRPC service keeps the client experience
    simple (one stub) while the IMPLEMENTATION routes commands to the Postgres
    write repo and queries to the Redis read repo. If read and write needed
    independent scaling/deploys we could split them into two services later —
    the proto is structured (clear COMMAND vs QUERY grouping below) so that
    split would be mechanical. This is the pragmatic "logical CQRS, physical
    monolith-of-one-service" choice MLflow's registry also makes.

    STREAMING CHOICE — why everything here is UNARY:
    None of these operations is a long-lived stream. Registrations and
    promotions are discrete commands; lookups return a bounded object; lists are
    PAGINATED (cursor) rather than server-streamed because pagination gives the
    client backpressure, resumability (the page_token survives a disconnect),
    and cacheability that a server stream does not. Contrast with the Pipeline
    Orchestrator's WatchExecution, which IS server-streaming because execution
    progress is a genuine open-ended event feed. Picking unary+pagination here
    is the correct, defensible call (interviewers probe this: "why not stream
    ListModels?" → backpressure + resumable cursor + simpler caching).

    RPC GROUPS:
    COMMANDS (Postgres write, then publish a canonical events.v1 NATS event):
    RegisterModel, UpdateModel, CreateVersion, ConfirmVersionUpload,
    PromoteVersion, DeleteModel
    QUERIES (Redis read projection, eventually consistent):
    GetModel, ListModels, SearchByTag, GetVersion, ListVersions
    STORAGE (object store, presigned URLs — bytes bypass this service):
    GetUploadURL (re-issue), GetDownloadURL  (the FIRST upload URL is returned
    inline by CreateVersion; GetUploadURL re-issues an expired one)
    ============================================================================
    --- COMMANDS (write path → Postgres → NATS event) ---
    """

    def RegisterModel(self, request, context):
        """RegisterModel creates a new model (the identity, no versions yet). Writes to
        Postgres and publishes events.ModelRegistered (fp.models.registered).
        owner_id/team are taken from the caller's auth claims, never the request.
        Idempotent via idempotency_key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModel(self, request, context):
        """UpdateModel mutates the small mutable surface (description and/or tags) of an
        existing model, using explicit update_description/replace_tags flags so an
        omitted field never silently clears stored data. name/owner/team/timestamps
        are NOT mutable here (mass-assignment guard). Publishes NO canonical event —
        these edits are not a published platform fact — but refreshes the read model.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVersion(self, request, context):
        """CreateVersion cuts a new immutable version of an existing model. Writes the
        version row (status=PENDING_UPLOAD, stage=DEV), returns a presigned upload
        URL for the artifact, and publishes events.ModelVersionCreated
        (fp.models.version.created). The artifact bytes never flow through this RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmVersionUpload(self, request, context):
        """ConfirmVersionUpload drives the PENDING_UPLOAD → READY (or FAILED) transition
        after the artifact has been PUT directly to object storage. The server
        RE-VERIFIES the object (existence + server-measured digest + size — never a
        client-asserted value), and on success flips status to READY and publishes
        events.ModelVersionReady (fp.models.version.ready) carrying the server-measured
        artifact_path/artifact_digest/size_bytes that serving/billing/orchestrator
        need. This is the READY edge that was previously unreachable (conflict #3).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteVersion(self, request, context):
        """PromoteVersion advances a version through the stage state machine
        (DEV→STAGING→PRODUCTION→ARCHIVED), enforcing legal transitions and the
        single-production invariant in ONE Postgres transaction, then publishes
        events.ModelPromoted (fp.models.promoted). This is what drives
        serving/gateway/monitor/billing reactions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """DeleteModel soft-deletes (archives) a model and all its versions, removes it
        from active read lists, and publishes events.ModelArchived
        (fp.models.archived). Rows are retained for lineage/audit — not a hard delete.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """--- QUERIES (read path → Redis projection; EVENTUALLY CONSISTENT) ---

        GetModel returns a single model by id or name from the Redis read model.
        May briefly miss a just-registered model (projection lag).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """ListModels returns a paginated, team-scoped page of models from the read
        model, newest-first, with optional task_type/framework filters. page_size is
        capped at 100 server-side.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByTag(self, request, context):
        """SearchByTag returns models matching a (key,value) tag, served from the
        projection's per-tag Redis set. Paginated, 100-item cap.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """GetVersion returns a single version by id, or by (model_id, version) label,
        from the read model.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVersions(self, request, context):
        """ListVersions returns a paginated, newest-first list of a model's versions
        from the read model, optionally filtered by stage. 100-item cap.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUploadURL(self, request, context):
        """--- STORAGE (object store; bytes bypass this control-plane service) ---

        GetUploadURL re-issues a fresh presigned PUT URL for an existing version that
        is still PENDING_UPLOAD (e.g. the original URL from CreateVersion expired, or
        the client crashed before uploading). Makes the upload step resumable without
        minting a duplicate version. Rejected if the version is already READY/FAILED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDownloadURL(self, request, context):
        """GetDownloadURL returns a short-lived presigned URL to fetch a READY
        version's artifact directly from MinIO/S3, plus the expected digest for
        integrity verification. Read-only and safe to retry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.RegisterModelRequest.FromString,
                    response_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.RegisterModelResponse.SerializeToString,
            ),
            'UpdateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModel,
                    request_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.UpdateModelRequest.FromString,
                    response_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.UpdateModelResponse.SerializeToString,
            ),
            'CreateVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVersion,
                    request_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.CreateVersionRequest.FromString,
                    response_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.CreateVersionResponse.SerializeToString,
            ),
            'ConfirmVersionUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmVersionUpload,
                    request_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.ConfirmVersionUploadRequest.FromString,
                    response_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.ConfirmVersionUploadResponse.SerializeToString,
            ),
            'PromoteVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteVersion,
                    request_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.PromoteVersionRequest.FromString,
                    response_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.PromoteVersionResponse.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.DeleteModelRequest.FromString,
                    response_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.DeleteModelResponse.SerializeToString,
            ),
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetModelRequest.FromString,
                    response_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetModelResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.ListModelsRequest.FromString,
                    response_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.ListModelsResponse.SerializeToString,
            ),
            'SearchByTag': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByTag,
                    request_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.SearchByTagRequest.FromString,
                    response_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.SearchByTagResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetVersionRequest.FromString,
                    response_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetVersionResponse.SerializeToString,
            ),
            'ListVersions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVersions,
                    request_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.ListVersionsRequest.FromString,
                    response_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.ListVersionsResponse.SerializeToString,
            ),
            'GetUploadURL': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUploadURL,
                    request_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetUploadURLRequest.FromString,
                    response_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetUploadURLResponse.SerializeToString,
            ),
            'GetDownloadURL': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDownloadURL,
                    request_deserializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetDownloadURLRequest.FromString,
                    response_serializer=forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetDownloadURLResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forgepoint.registry.v1.RegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forgepoint.registry.v1.RegistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegistryService:
    """============================================================================
    EVENTS THIS SERVICE PUBLISHES — defined in forgepoint.events.v1, NOT here
    ============================================================================

    WHY THERE ARE NO EVENT MESSAGES IN THIS FILE ANYMORE (this is deliberate):
    This proto previously defined its OWN ModelRegistered / ModelVersionCreated /
    ModelPromoted / ModelArchived payloads. An adversarial cross-service review
    found per-service event messages DRIFTING from the consumers that read them
    (mismatched names, missing fields, two services both claiming one event).
    The fix: ONE canonical event package, forgepoint.events.v1, owned and
    buf-breaking-guarded independently of any service's API. Those four ad-hoc
    messages have been DELETED from this file and now live, canonically, in
    proto/forgepoint/events/v1/events.proto. The registry handler marshals an
    eventsv1.* message into common.v1.EventEnvelope.data (an Any) at publish time.

    This also realizes the "event schema is DECOUPLED from API schema" rule: the
    old registry events EMBEDDED the full registry.Model / registry.ModelVersion,
    which coupled every consumer's build to this proto. The canonical events
    instead carry FLAT ids + the specific fields consumers need, so a consumer
    depends only on eventsv1 + common — never on registry's API types.

    THE FIVE EVENTS REGISTRY PRODUCES (subject · canonical message · key consumers):
    fp.models.registered       · events.ModelRegistered     · pipeline-orchestrator, experiment-tracker
    fp.models.version.created  · events.ModelVersionCreated · experiment-tracker
    fp.models.version.ready    · events.ModelVersionReady   · serving, billing, pipeline-orchestrator   (NEW)
    fp.models.promoted         · events.ModelPromoted       · inference-gateway, serving, model-monitor, billing
    fp.models.archived         · events.ModelArchived       · inference-gateway, serving, billing

    RPC → EVENT(S) it emits on commit:
    RegisterModel        → events.ModelRegistered
    CreateVersion        → events.ModelVersionCreated   (status=PENDING_UPLOAD)
    ConfirmVersionUpload → events.ModelVersionReady     (status PENDING_UPLOAD→READY; NONE on →FAILED)
    PromoteVersion       → events.ModelPromoted         (carries from/to + demoted version — the atomic swap)
    DeleteModel          → events.ModelArchived
    UpdateModel          → (no canonical event — description/tag edits aren't a published fact)

    ENUM MAPPING AT THE BOUNDARY: registry.ModelStage values are mapped to the
    mirror events.ModelStage explicitly in the handler (not cast), per the
    decoupling note on the ModelStage enum above. CONSUMERS that need the
    PENDING_UPLOAD→READY distinction watch ModelVersionReady, NOT ModelVersionCreated.

    REGISTRY CONSUMES NO EVENTS. Its read-side projection consumer reacts to its
    OWN published events to build the Redis read model (the CQRS loop), but the
    service subscribes to no OTHER service's events — there is no inbound coupling.
    ============================================================================

    ============================================================================
    REGISTRY SERVICE
    ============================================================================

    WHY a single RegistryService spanning both command and query RPCs:
    CQRS separates the read/write MODELS and STORES, not necessarily the API
    surface. Exposing both through one gRPC service keeps the client experience
    simple (one stub) while the IMPLEMENTATION routes commands to the Postgres
    write repo and queries to the Redis read repo. If read and write needed
    independent scaling/deploys we could split them into two services later —
    the proto is structured (clear COMMAND vs QUERY grouping below) so that
    split would be mechanical. This is the pragmatic "logical CQRS, physical
    monolith-of-one-service" choice MLflow's registry also makes.

    STREAMING CHOICE — why everything here is UNARY:
    None of these operations is a long-lived stream. Registrations and
    promotions are discrete commands; lookups return a bounded object; lists are
    PAGINATED (cursor) rather than server-streamed because pagination gives the
    client backpressure, resumability (the page_token survives a disconnect),
    and cacheability that a server stream does not. Contrast with the Pipeline
    Orchestrator's WatchExecution, which IS server-streaming because execution
    progress is a genuine open-ended event feed. Picking unary+pagination here
    is the correct, defensible call (interviewers probe this: "why not stream
    ListModels?" → backpressure + resumable cursor + simpler caching).

    RPC GROUPS:
    COMMANDS (Postgres write, then publish a canonical events.v1 NATS event):
    RegisterModel, UpdateModel, CreateVersion, ConfirmVersionUpload,
    PromoteVersion, DeleteModel
    QUERIES (Redis read projection, eventually consistent):
    GetModel, ListModels, SearchByTag, GetVersion, ListVersions
    STORAGE (object store, presigned URLs — bytes bypass this service):
    GetUploadURL (re-issue), GetDownloadURL  (the FIRST upload URL is returned
    inline by CreateVersion; GetUploadURL re-issues an expired one)
    ============================================================================
    --- COMMANDS (write path → Postgres → NATS event) ---
    """

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.registry.v1.RegistryService/RegisterModel',
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.RegisterModelRequest.SerializeToString,
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.RegisterModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.registry.v1.RegistryService/UpdateModel',
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.UpdateModelRequest.SerializeToString,
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.UpdateModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.registry.v1.RegistryService/CreateVersion',
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.CreateVersionRequest.SerializeToString,
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.CreateVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmVersionUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.registry.v1.RegistryService/ConfirmVersionUpload',
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.ConfirmVersionUploadRequest.SerializeToString,
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.ConfirmVersionUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.registry.v1.RegistryService/PromoteVersion',
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.PromoteVersionRequest.SerializeToString,
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.PromoteVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.registry.v1.RegistryService/DeleteModel',
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.DeleteModelRequest.SerializeToString,
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.DeleteModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.registry.v1.RegistryService/GetModel',
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetModelRequest.SerializeToString,
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.registry.v1.RegistryService/ListModels',
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.ListModelsRequest.SerializeToString,
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchByTag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.registry.v1.RegistryService/SearchByTag',
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.SearchByTagRequest.SerializeToString,
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.SearchByTagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.registry.v1.RegistryService/GetVersion',
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetVersionRequest.SerializeToString,
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVersions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.registry.v1.RegistryService/ListVersions',
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.ListVersionsRequest.SerializeToString,
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.ListVersionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUploadURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.registry.v1.RegistryService/GetUploadURL',
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetUploadURLRequest.SerializeToString,
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetUploadURLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDownloadURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.registry.v1.RegistryService/GetDownloadURL',
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetDownloadURLRequest.SerializeToString,
            forgepoint_dot_registry_dot_v1_dot_registry__pb2.GetDownloadURLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
