# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from forgepoint.auth.v1 import auth_pb2 as forgepoint_dot_auth_dot_v1_dot_auth__pb2


class AuthServiceStub:
    """============================================================================
    AUTH SERVICE
    ============================================================================

    WHY a single AuthService vs separate UserService, TokenService, etc.:
    Identity, credentials, and access control are tightly coupled. Splitting
    them into separate services would require inter-service calls for common
    flows (e.g., Login needs User lookup, token issuance, and permission
    loading). A single AuthService keeps the auth boundary clean.

    Real-world parallel: Keycloak, Auth0, and Ory Kratos all handle user
    management + token issuance in a single service boundary. The split only
    makes sense at org scale (separate teams owning identity vs. access control).

    RPC CATEGORIES:
    IDENTITY MANAGEMENT: CreateUser, ListUsers
    CREDENTIALS: Login, CreateAPIKey, RevokeAPIKey
    TOKEN VALIDATION: ValidateToken (called by every other service's interceptor)
    ACCESS CONTROL: CheckPermission, AssignRole

    INTERCEPTOR CALL PATTERN:
    Every gRPC service in Forgepoint has an auth interceptor that:
    1. Extracts "authorization: Bearer <token>" from incoming metadata
    2. Calls AuthService.ValidateToken() → gets TokenClaims
    3. Calls AuthService.CheckPermission() with the resource+action for that RPC
    4. Injects TokenClaims into gRPC context for handler use
    The interceptor is registered via grpc.ChainUnaryInterceptor in pkg/grpcutil.

    ASCII DIAGRAM — Token Validation Flow:

    gRPC Client
    │ metadata: authorization=Bearer <jwt>
    ▼
    ModelRegistry gRPC Server
    │
    ├─ Recovery Interceptor (panic → gRPC Internal)
    ├─ Logging Interceptor (structured log per RPC)
    ├─ Tracing Interceptor (OpenTelemetry span)
    └─ Auth Interceptor ──► AuthService.ValidateToken(token)
    ──► AuthService.CheckPermission(user_id, "models", "write")
    ──► injects claims into ctx
    │
    ▼
    Handler (sees claims via ctx)
    ============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/forgepoint.auth.v1.AuthService/Login',
                request_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.LoginRequest.SerializeToString,
                response_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/forgepoint.auth.v1.AuthService/CreateUser',
                request_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/forgepoint.auth.v1.AuthService/ListUsers',
                request_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.CreateAPIKey = channel.unary_unary(
                '/forgepoint.auth.v1.AuthService/CreateAPIKey',
                request_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.CreateAPIKeyRequest.SerializeToString,
                response_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.CreateAPIKeyResponse.FromString,
                _registered_method=True)
        self.RevokeAPIKey = channel.unary_unary(
                '/forgepoint.auth.v1.AuthService/RevokeAPIKey',
                request_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.RevokeAPIKeyRequest.SerializeToString,
                response_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.RevokeAPIKeyResponse.FromString,
                _registered_method=True)
        self.ValidateToken = channel.unary_unary(
                '/forgepoint.auth.v1.AuthService/ValidateToken',
                request_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.ValidateTokenResponse.FromString,
                _registered_method=True)
        self.CheckPermission = channel.unary_unary(
                '/forgepoint.auth.v1.AuthService/CheckPermission',
                request_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.CheckPermissionRequest.SerializeToString,
                response_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.CheckPermissionResponse.FromString,
                _registered_method=True)
        self.AssignRole = channel.unary_unary(
                '/forgepoint.auth.v1.AuthService/AssignRole',
                request_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.AssignRoleRequest.SerializeToString,
                response_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.AssignRoleResponse.FromString,
                _registered_method=True)


class AuthServiceServicer:
    """============================================================================
    AUTH SERVICE
    ============================================================================

    WHY a single AuthService vs separate UserService, TokenService, etc.:
    Identity, credentials, and access control are tightly coupled. Splitting
    them into separate services would require inter-service calls for common
    flows (e.g., Login needs User lookup, token issuance, and permission
    loading). A single AuthService keeps the auth boundary clean.

    Real-world parallel: Keycloak, Auth0, and Ory Kratos all handle user
    management + token issuance in a single service boundary. The split only
    makes sense at org scale (separate teams owning identity vs. access control).

    RPC CATEGORIES:
    IDENTITY MANAGEMENT: CreateUser, ListUsers
    CREDENTIALS: Login, CreateAPIKey, RevokeAPIKey
    TOKEN VALIDATION: ValidateToken (called by every other service's interceptor)
    ACCESS CONTROL: CheckPermission, AssignRole

    INTERCEPTOR CALL PATTERN:
    Every gRPC service in Forgepoint has an auth interceptor that:
    1. Extracts "authorization: Bearer <token>" from incoming metadata
    2. Calls AuthService.ValidateToken() → gets TokenClaims
    3. Calls AuthService.CheckPermission() with the resource+action for that RPC
    4. Injects TokenClaims into gRPC context for handler use
    The interceptor is registered via grpc.ChainUnaryInterceptor in pkg/grpcutil.

    ASCII DIAGRAM — Token Validation Flow:

    gRPC Client
    │ metadata: authorization=Bearer <jwt>
    ▼
    ModelRegistry gRPC Server
    │
    ├─ Recovery Interceptor (panic → gRPC Internal)
    ├─ Logging Interceptor (structured log per RPC)
    ├─ Tracing Interceptor (OpenTelemetry span)
    └─ Auth Interceptor ──► AuthService.ValidateToken(token)
    ──► AuthService.CheckPermission(user_id, "models", "write")
    ──► injects claims into ctx
    │
    ▼
    Handler (sees claims via ctx)
    ============================================================================
    """

    def Login(self, request, context):
        """Login authenticates a user with email + password and returns a signed JWT.
        This is the entry point for human users (CLI login, web UI login).
        For machine-to-machine auth, use API keys instead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """CreateUser provisions a new user account. Requires admin role.
        Password is bcrypt-hashed before storage. Returns the user profile (no
        password field — passwords are write-only).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """ListUsers returns a paginated list of users. Requires admin role.
        Supports filtering by team via ListUsersRequest.team_filter.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAPIKey(self, request, context):
        """CreateAPIKey creates a new API key for a user.
        The raw key is returned ONCE in CreateAPIKeyResponse.raw_key.
        After that, only the key_prefix is visible (for identification in UI).
        Use API keys for CI/CD pipelines, training scripts, and SDK clients.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAPIKey(self, request, context):
        """RevokeAPIKey immediately invalidates an API key by ID.
        Revocation takes effect immediately — the next request using this key
        will receive UNAUTHENTICATED. No expiry window; this is why centralized
        auth beats distributed JWT validation for revocability.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """ValidateToken is the workhorse called by auth interceptors in ALL other
        services. It validates the JWT signature, checks expiry, verifies the
        token is not in the revocation blacklist, and returns decoded TokenClaims.

        Performance note: the auth service caches validation results in Redis
        with a 30-second TTL. This keeps auth overhead below 1ms p99 while
        still enforcing near-real-time revocation.

        NOTE — what happens if the auth service goes down: the other services'
        interceptors can be configured with a fail-open (allow) or fail-closed (deny) policy. Forgepoint uses
        fail-closed (safe default for a security service). A circuit breaker on
        the auth gRPC client prevents cascade failures during auth service outages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPermission(self, request, context):
        """CheckPermission evaluates whether a user's role permits a specific
        resource+action. Called by auth interceptors after ValidateToken to
        enforce RBAC. Returns allowed bool + human-readable reason.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignRole(self, request, context):
        """AssignRole changes a user's role. Requires admin permission.
        NOTE: The newly assigned role takes effect on the NEXT token issuance —
        existing JWTs retain the old role until they expire (or are revoked).
        For immediate role change enforcement, also revoke the user's existing tokens.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.LoginRequest.FromString,
                    response_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.LoginResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.CreateUserRequest.FromString,
                    response_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.CreateUserResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.ListUsersRequest.FromString,
                    response_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.ListUsersResponse.SerializeToString,
            ),
            'CreateAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAPIKey,
                    request_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.CreateAPIKeyRequest.FromString,
                    response_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.CreateAPIKeyResponse.SerializeToString,
            ),
            'RevokeAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAPIKey,
                    request_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.RevokeAPIKeyRequest.FromString,
                    response_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.RevokeAPIKeyResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.ValidateTokenRequest.FromString,
                    response_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.ValidateTokenResponse.SerializeToString,
            ),
            'CheckPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPermission,
                    request_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.CheckPermissionRequest.FromString,
                    response_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.CheckPermissionResponse.SerializeToString,
            ),
            'AssignRole': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignRole,
                    request_deserializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.AssignRoleRequest.FromString,
                    response_serializer=forgepoint_dot_auth_dot_v1_dot_auth__pb2.AssignRoleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forgepoint.auth.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forgepoint.auth.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService:
    """============================================================================
    AUTH SERVICE
    ============================================================================

    WHY a single AuthService vs separate UserService, TokenService, etc.:
    Identity, credentials, and access control are tightly coupled. Splitting
    them into separate services would require inter-service calls for common
    flows (e.g., Login needs User lookup, token issuance, and permission
    loading). A single AuthService keeps the auth boundary clean.

    Real-world parallel: Keycloak, Auth0, and Ory Kratos all handle user
    management + token issuance in a single service boundary. The split only
    makes sense at org scale (separate teams owning identity vs. access control).

    RPC CATEGORIES:
    IDENTITY MANAGEMENT: CreateUser, ListUsers
    CREDENTIALS: Login, CreateAPIKey, RevokeAPIKey
    TOKEN VALIDATION: ValidateToken (called by every other service's interceptor)
    ACCESS CONTROL: CheckPermission, AssignRole

    INTERCEPTOR CALL PATTERN:
    Every gRPC service in Forgepoint has an auth interceptor that:
    1. Extracts "authorization: Bearer <token>" from incoming metadata
    2. Calls AuthService.ValidateToken() → gets TokenClaims
    3. Calls AuthService.CheckPermission() with the resource+action for that RPC
    4. Injects TokenClaims into gRPC context for handler use
    The interceptor is registered via grpc.ChainUnaryInterceptor in pkg/grpcutil.

    ASCII DIAGRAM — Token Validation Flow:

    gRPC Client
    │ metadata: authorization=Bearer <jwt>
    ▼
    ModelRegistry gRPC Server
    │
    ├─ Recovery Interceptor (panic → gRPC Internal)
    ├─ Logging Interceptor (structured log per RPC)
    ├─ Tracing Interceptor (OpenTelemetry span)
    └─ Auth Interceptor ──► AuthService.ValidateToken(token)
    ──► AuthService.CheckPermission(user_id, "models", "write")
    ──► injects claims into ctx
    │
    ▼
    Handler (sees claims via ctx)
    ============================================================================
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.auth.v1.AuthService/Login',
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.LoginRequest.SerializeToString,
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.auth.v1.AuthService/CreateUser',
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.CreateUserRequest.SerializeToString,
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.auth.v1.AuthService/ListUsers',
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.ListUsersRequest.SerializeToString,
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.auth.v1.AuthService/CreateAPIKey',
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.CreateAPIKeyRequest.SerializeToString,
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.CreateAPIKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.auth.v1.AuthService/RevokeAPIKey',
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.RevokeAPIKeyRequest.SerializeToString,
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.RevokeAPIKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.auth.v1.AuthService/ValidateToken',
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.ValidateTokenRequest.SerializeToString,
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.ValidateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.auth.v1.AuthService/CheckPermission',
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.CheckPermissionRequest.SerializeToString,
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.CheckPermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.auth.v1.AuthService/AssignRole',
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.AssignRoleRequest.SerializeToString,
            forgepoint_dot_auth_dot_v1_dot_auth__pb2.AssignRoleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
