# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: forgepoint/common/v1/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'forgepoint/common/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!forgepoint/common/v1/common.proto\x12\x14\x66orgepoint.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xd6\x01\n\rEventEnvelope\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n\x06source\x18\x03 \x01(\tR\x06source\x12\x38\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\ttimestamp\x12%\n\x0e\x63orrelation_id\x18\x05 \x01(\tR\rcorrelationId\x12(\n\x04\x64\x61ta\x18\x06 \x01(\x0b\x32\x14.google.protobuf.AnyR\x04\x64\x61ta\"O\n\x11PaginationRequest\x12\x1b\n\tpage_size\x18\x01 \x01(\x05R\x08pageSize\x12\x1d\n\npage_token\x18\x02 \x01(\tR\tpageToken\"]\n\x12PaginationResponse\x12&\n\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12\x1f\n\x0btotal_count\x18\x02 \x01(\x05R\ntotalCount\"Q\n\x0b\x45rrorDetail\x12\x12\n\x04\x63ode\x18\x01 \x01(\tR\x04\x63ode\x12\x18\n\x07message\x18\x02 \x01(\tR\x07message\x12\x14\n\x05\x66ield\x18\x03 \x01(\tR\x05\x66ieldB\xe1\x01\n\x18\x63om.forgepoint.common.v1B\x0b\x43ommonProtoP\x01ZFgithub.com/abd-ulbasit/forgepoint/gen/go/forgepoint/common/v1;commonv1\xa2\x02\x03\x46\x43X\xaa\x02\x14\x46orgepoint.Common.V1\xca\x02\x14\x46orgepoint\\Common\\V1\xe2\x02 Forgepoint\\Common\\V1\\GPBMetadata\xea\x02\x16\x46orgepoint::Common::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'forgepoint.common.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.forgepoint.common.v1B\013CommonProtoP\001ZFgithub.com/abd-ulbasit/forgepoint/gen/go/forgepoint/common/v1;commonv1\242\002\003FCX\252\002\024Forgepoint.Common.V1\312\002\024Forgepoint\\Common\\V1\342\002 Forgepoint\\Common\\V1\\GPBMetadata\352\002\026Forgepoint::Common::V1'
  _globals['_EVENTENVELOPE']._serialized_start=120
  _globals['_EVENTENVELOPE']._serialized_end=334
  _globals['_PAGINATIONREQUEST']._serialized_start=336
  _globals['_PAGINATIONREQUEST']._serialized_end=415
  _globals['_PAGINATIONRESPONSE']._serialized_start=417
  _globals['_PAGINATIONRESPONSE']._serialized_end=510
  _globals['_ERRORDETAIL']._serialized_start=512
  _globals['_ERRORDETAIL']._serialized_end=593
# @@protoc_insertion_point(module_scope)
