# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from forgepoint.notification.v1 import notification_pb2 as forgepoint_dot_notification_dot_v1_dot_notification__pb2


class NotificationServiceStub:
    """============================================================================
    NOTIFICATION SERVICE
    ============================================================================

    WHY a single small NotificationService: as explained at the top, this is the
    CONTROL PLANE only. The real engine — subscribe to `fp.>`, match preferences,
    deliver with retries + circuit breaker, write the delivery log — runs on the
    NATS path and exposes NOTHING synchronous. There is intentionally no
    "send"/"trigger" RPC: a producer calling us would break choreography.

    RPC CATEGORIES:
    INBOX (read model):   ListNotifications, GetNotification, MarkRead
    DELIVERY LOG (audit): ListDeliveryAttempts
    PREFERENCES (config): GetPreferences, UpdatePreferences, TestChannel
    (TestChannel is a control-plane self-check, not a "send" RPC — see its doc.)

    WHY NO STREAMING RPC HERE (a deliberate choice, interview-relevant):
    A live "watch my inbox" stream is tempting, but the natural realtime path
    for notifications is the very NATS stream this service already consumes and
    the fan-out channels (web push, Slack) it already delivers over. The web UI
    gets realtime via the BFF bridging `fp.notifications.>` to Server-Sent
    Events — NOT via a gRPC server-stream on this service. So the gRPC surface
    stays request/response (inbox + settings), and we avoid maintaining
    long-lived per-client streams on a service whose whole point is to be a
    stateless event reactor. Contrast: the Pipeline Orchestrator DOES expose a
    WatchExecution server-stream, because there the authoritative state lives in
    that service and a client genuinely needs to follow one execution's lifecycle.

    IDEMPOTENCY (interview-critical, on BOTH paths):
    - Async consumer: events can be redelivered (NATS at-least-once). The
    consumer dedupes on EventEnvelope.id (carried into Notification.event_id)
    per recipient, so a redelivered event never creates a duplicate inbox row
    or a duplicate delivery. This is the "idempotent consumer" platform rule.
    - Sync mutation: UpdatePreferences takes an idempotency_key so client retries
    are safe. MarkRead is naturally idempotent (read→read is a no-op), so it
    needs no key.
    ============================================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListNotifications = channel.unary_unary(
                '/forgepoint.notification.v1.NotificationService/ListNotifications',
                request_serializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.ListNotificationsRequest.SerializeToString,
                response_deserializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.ListNotificationsResponse.FromString,
                _registered_method=True)
        self.GetNotification = channel.unary_unary(
                '/forgepoint.notification.v1.NotificationService/GetNotification',
                request_serializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.GetNotificationRequest.SerializeToString,
                response_deserializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.GetNotificationResponse.FromString,
                _registered_method=True)
        self.MarkRead = channel.unary_unary(
                '/forgepoint.notification.v1.NotificationService/MarkRead',
                request_serializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.MarkReadRequest.SerializeToString,
                response_deserializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.MarkReadResponse.FromString,
                _registered_method=True)
        self.ListDeliveryAttempts = channel.unary_unary(
                '/forgepoint.notification.v1.NotificationService/ListDeliveryAttempts',
                request_serializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.ListDeliveryAttemptsRequest.SerializeToString,
                response_deserializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.ListDeliveryAttemptsResponse.FromString,
                _registered_method=True)
        self.GetPreferences = channel.unary_unary(
                '/forgepoint.notification.v1.NotificationService/GetPreferences',
                request_serializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.GetPreferencesRequest.SerializeToString,
                response_deserializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.GetPreferencesResponse.FromString,
                _registered_method=True)
        self.UpdatePreferences = channel.unary_unary(
                '/forgepoint.notification.v1.NotificationService/UpdatePreferences',
                request_serializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.UpdatePreferencesRequest.SerializeToString,
                response_deserializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.UpdatePreferencesResponse.FromString,
                _registered_method=True)
        self.TestChannel = channel.unary_unary(
                '/forgepoint.notification.v1.NotificationService/TestChannel',
                request_serializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.TestChannelRequest.SerializeToString,
                response_deserializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.TestChannelResponse.FromString,
                _registered_method=True)


class NotificationServiceServicer:
    """============================================================================
    NOTIFICATION SERVICE
    ============================================================================

    WHY a single small NotificationService: as explained at the top, this is the
    CONTROL PLANE only. The real engine — subscribe to `fp.>`, match preferences,
    deliver with retries + circuit breaker, write the delivery log — runs on the
    NATS path and exposes NOTHING synchronous. There is intentionally no
    "send"/"trigger" RPC: a producer calling us would break choreography.

    RPC CATEGORIES:
    INBOX (read model):   ListNotifications, GetNotification, MarkRead
    DELIVERY LOG (audit): ListDeliveryAttempts
    PREFERENCES (config): GetPreferences, UpdatePreferences, TestChannel
    (TestChannel is a control-plane self-check, not a "send" RPC — see its doc.)

    WHY NO STREAMING RPC HERE (a deliberate choice, interview-relevant):
    A live "watch my inbox" stream is tempting, but the natural realtime path
    for notifications is the very NATS stream this service already consumes and
    the fan-out channels (web push, Slack) it already delivers over. The web UI
    gets realtime via the BFF bridging `fp.notifications.>` to Server-Sent
    Events — NOT via a gRPC server-stream on this service. So the gRPC surface
    stays request/response (inbox + settings), and we avoid maintaining
    long-lived per-client streams on a service whose whole point is to be a
    stateless event reactor. Contrast: the Pipeline Orchestrator DOES expose a
    WatchExecution server-stream, because there the authoritative state lives in
    that service and a client genuinely needs to follow one execution's lifecycle.

    IDEMPOTENCY (interview-critical, on BOTH paths):
    - Async consumer: events can be redelivered (NATS at-least-once). The
    consumer dedupes on EventEnvelope.id (carried into Notification.event_id)
    per recipient, so a redelivered event never creates a duplicate inbox row
    or a duplicate delivery. This is the "idempotent consumer" platform rule.
    - Sync mutation: UpdatePreferences takes an idempotency_key so client retries
    are safe. MarkRead is naturally idempotent (read→read is a no-op), so it
    needs no key.
    ============================================================================
    """

    def ListNotifications(self, request, context):
        """ListNotifications returns a paginated page of the AUTHENTICATED caller's
        inbox (newest first), with optional unread/severity/event-type filters and
        an unread_count for the UI badge. Scoped to the caller — never another user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNotification(self, request, context):
        """GetNotification fetches one of the caller's notifications in full, including
        its per-channel delivery attempt history (the delivery_log). Returns
        NOT_FOUND for ids that don't exist OR belong to another user (so existence
        of another user's notification isn't leaked).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkRead(self, request, context):
        """MarkRead marks one, many, or all of the caller's notifications as read and
        returns the new unread count. Naturally idempotent (marking a read item read
        is a no-op), so no idempotency key is required. Foreign/unknown ids are
        skipped rather than failing the batch.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDeliveryAttempts(self, request, context):
        """ListDeliveryAttempts returns a paginated page of the caller's delivery log
        (the GetDeliveryLog surface the plan calls for) — the cross-notification view
        for "did my alerts go out, which failed?", with optional channel/status/
        notification filters. Scoped to the caller; secrets/targets are never echoed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPreferences(self, request, context):
        """GetPreferences returns the caller's notification preferences (per-channel
        settings + mute patterns), falling back to sensible defaults if the user has
        never configured any. Always the caller's own preferences.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePreferences(self, request, context):
        """UpdatePreferences replaces the caller's preferences wholesale (PUT
        semantics) and returns the stored result. Accepts an optional idempotency
        key so retries are safe. The target user is always the caller — the request
        body cannot reassign ownership. Every webhook/slack target is SSRF-validated
        server-side before persisting (see ChannelPreference.target).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestChannel(self, request, context):
        """TestChannel sends a synthetic test notification to one of the CALLER'S OWN
        configured channels so the settings UI can confirm it works. This is a
        control-plane self-check (the owner testing their own delivery config), NOT a
        producer-facing "send" RPC — it carries no target URL and addresses no other
        user, so it neither violates choreography nor opens an SSRF vector. Accepts an
        idempotency key so a retry doesn't double-fire the test.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListNotifications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNotifications,
                    request_deserializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.ListNotificationsRequest.FromString,
                    response_serializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.ListNotificationsResponse.SerializeToString,
            ),
            'GetNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNotification,
                    request_deserializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.GetNotificationRequest.FromString,
                    response_serializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.GetNotificationResponse.SerializeToString,
            ),
            'MarkRead': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkRead,
                    request_deserializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.MarkReadRequest.FromString,
                    response_serializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.MarkReadResponse.SerializeToString,
            ),
            'ListDeliveryAttempts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDeliveryAttempts,
                    request_deserializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.ListDeliveryAttemptsRequest.FromString,
                    response_serializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.ListDeliveryAttemptsResponse.SerializeToString,
            ),
            'GetPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPreferences,
                    request_deserializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.GetPreferencesRequest.FromString,
                    response_serializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.GetPreferencesResponse.SerializeToString,
            ),
            'UpdatePreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePreferences,
                    request_deserializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.UpdatePreferencesRequest.FromString,
                    response_serializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.UpdatePreferencesResponse.SerializeToString,
            ),
            'TestChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.TestChannel,
                    request_deserializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.TestChannelRequest.FromString,
                    response_serializer=forgepoint_dot_notification_dot_v1_dot_notification__pb2.TestChannelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forgepoint.notification.v1.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forgepoint.notification.v1.NotificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificationService:
    """============================================================================
    NOTIFICATION SERVICE
    ============================================================================

    WHY a single small NotificationService: as explained at the top, this is the
    CONTROL PLANE only. The real engine — subscribe to `fp.>`, match preferences,
    deliver with retries + circuit breaker, write the delivery log — runs on the
    NATS path and exposes NOTHING synchronous. There is intentionally no
    "send"/"trigger" RPC: a producer calling us would break choreography.

    RPC CATEGORIES:
    INBOX (read model):   ListNotifications, GetNotification, MarkRead
    DELIVERY LOG (audit): ListDeliveryAttempts
    PREFERENCES (config): GetPreferences, UpdatePreferences, TestChannel
    (TestChannel is a control-plane self-check, not a "send" RPC — see its doc.)

    WHY NO STREAMING RPC HERE (a deliberate choice, interview-relevant):
    A live "watch my inbox" stream is tempting, but the natural realtime path
    for notifications is the very NATS stream this service already consumes and
    the fan-out channels (web push, Slack) it already delivers over. The web UI
    gets realtime via the BFF bridging `fp.notifications.>` to Server-Sent
    Events — NOT via a gRPC server-stream on this service. So the gRPC surface
    stays request/response (inbox + settings), and we avoid maintaining
    long-lived per-client streams on a service whose whole point is to be a
    stateless event reactor. Contrast: the Pipeline Orchestrator DOES expose a
    WatchExecution server-stream, because there the authoritative state lives in
    that service and a client genuinely needs to follow one execution's lifecycle.

    IDEMPOTENCY (interview-critical, on BOTH paths):
    - Async consumer: events can be redelivered (NATS at-least-once). The
    consumer dedupes on EventEnvelope.id (carried into Notification.event_id)
    per recipient, so a redelivered event never creates a duplicate inbox row
    or a duplicate delivery. This is the "idempotent consumer" platform rule.
    - Sync mutation: UpdatePreferences takes an idempotency_key so client retries
    are safe. MarkRead is naturally idempotent (read→read is a no-op), so it
    needs no key.
    ============================================================================
    """

    @staticmethod
    def ListNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.notification.v1.NotificationService/ListNotifications',
            forgepoint_dot_notification_dot_v1_dot_notification__pb2.ListNotificationsRequest.SerializeToString,
            forgepoint_dot_notification_dot_v1_dot_notification__pb2.ListNotificationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.notification.v1.NotificationService/GetNotification',
            forgepoint_dot_notification_dot_v1_dot_notification__pb2.GetNotificationRequest.SerializeToString,
            forgepoint_dot_notification_dot_v1_dot_notification__pb2.GetNotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.notification.v1.NotificationService/MarkRead',
            forgepoint_dot_notification_dot_v1_dot_notification__pb2.MarkReadRequest.SerializeToString,
            forgepoint_dot_notification_dot_v1_dot_notification__pb2.MarkReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDeliveryAttempts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.notification.v1.NotificationService/ListDeliveryAttempts',
            forgepoint_dot_notification_dot_v1_dot_notification__pb2.ListDeliveryAttemptsRequest.SerializeToString,
            forgepoint_dot_notification_dot_v1_dot_notification__pb2.ListDeliveryAttemptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.notification.v1.NotificationService/GetPreferences',
            forgepoint_dot_notification_dot_v1_dot_notification__pb2.GetPreferencesRequest.SerializeToString,
            forgepoint_dot_notification_dot_v1_dot_notification__pb2.GetPreferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.notification.v1.NotificationService/UpdatePreferences',
            forgepoint_dot_notification_dot_v1_dot_notification__pb2.UpdatePreferencesRequest.SerializeToString,
            forgepoint_dot_notification_dot_v1_dot_notification__pb2.UpdatePreferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forgepoint.notification.v1.NotificationService/TestChannel',
            forgepoint_dot_notification_dot_v1_dot_notification__pb2.TestChannelRequest.SerializeToString,
            forgepoint_dot_notification_dot_v1_dot_notification__pb2.TestChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
