# ============================================================================
# elasticache — INPUTS  (Redis)
# ============================================================================
# Redis backs the Model Registry CQRS read model and the Inference Gateway rate
# limiter (mirrors deploy/k8s/infra/redis). In the cloud it becomes ElastiCache
# for Redis: encrypted at rest AND in transit, private-subnet only, reachable
# only from EKS nodes, with an AUTH TOKEN generated by Terraform and stored in
# Secrets Manager (never an input, never an output).
# ============================================================================

variable "name_prefix" {
  description = "Name prefix, e.g. \"forgepoint-dev\". The replication group id is derived from it (and truncated — ElastiCache ids are <=40 chars)."
  type        = string
}

variable "vpc_id" {
  description = "VPC the cache lives in."
  type        = string
}

variable "private_subnet_ids" {
  description = "Private subnet IDs for the cache subnet group. Cache nodes are never public."
  type        = list(string)
}

variable "allowed_security_group_ids" {
  description = "SG IDs allowed to connect on 6379 — the EKS node SG in practice. SG-to-SG, so only our pods reach Redis."
  type        = list(string)
  default     = []
}

variable "engine_version" {
  description = "Redis engine version. Matches the local redis:7 family. Pin it."
  type        = string
  default     = "7.1"
}

variable "node_type" {
  description = "Cache node instance type. Dev: cache.t3.micro (smallest burstable, cheap). Prod tunes up (cache.r6g.*) and may add nodes."
  type        = string
  default     = "cache.t3.micro"
}

variable "num_cache_nodes" {
  description = "Number of nodes in the replication group (1 primary + N-1 replicas). Dev: 1 (no HA, cheapest — a dev cache loss just cold-starts). Prod: >=2 so automatic_failover can promote a replica."
  type        = number
  default     = 1
}

variable "automatic_failover" {
  description = "Promote a replica to primary automatically if the primary fails. Requires num_cache_nodes >= 2, so it MUST be false when num_cache_nodes == 1 (dev). Prod sets nodes>=2 and this true."
  type        = bool
  default     = false
}

variable "snapshot_retention_days" {
  description = "Days to keep daily RDB snapshots. 1 in dev (minimal); prod raises. 0 disables snapshots."
  type        = number
  default     = 1
}

variable "tags" {
  description = "Additional tags (Project/Environment/ManagedBy via provider default_tags)."
  type        = map(string)
  default     = {}
}
